"""案B: 基礎・機械学習（220語）。"""

# id, name, yomi, reading, summary, tier, exams
TERMS = [
    ('a-star-search', 'A*探索', 'A* Search', 'A', 'ヒューリスティックで効率的に最短経路を求める探索アルゴリズム。', 2, 'g-kentei'),
    ('ab-test-ml', 'A/Bテスト', 'A/B Test', 'A', '本番環境で2案を比較し効果を統計的に検証する手法。', 2, 'g-kentei'),
    ('agi', 'AGI', '汎用人工知能', '', '人間と同等以上の知的能力を持つとされるAI。現時点では実現していない概念上の目標として研究が進む。', 2, 'g-kentei'),
    ('ai-accelerator', 'AIアクセラレータ', 'AI Accelerator', 'A', '行列演算を高速化する専用チップ。GPUやTPUなど。', 2, 'g-kentei'),
    ('ai-boom', 'AIブーム', 'AI Boom', 'A', '技術進展や社会関心の高まりでAI投資が拡大する局面。', 2, 'g-kentei'),
    ('ai-winter', 'AI冬の時代', 'AI Winter', 'A', '期待過多と失望で研究資金が縮小した時期。二度の冬があった。', 2, 'g-kentei'),
    ('api', 'API', 'Application Programming Interface', '', '異なるソフトウェア同士が通信するための窓口。ChatGPTなど多くのAIサービスがAPIを公開しており、業務システムへの組み込みに活用される。', 2, 'g-kentei'),
    ('arima', 'ARIMA', 'ARIMA', 'A', '自己回帰と移動平均を組み合わせた古典的時系列モデル。', 2, 'g-kentei'),
    ('auc', 'AUC', 'Area Under Curve', 'A', 'ROC曲線下の面積。分類性能の総合指標。', 2, 'g-kentei'),
    ('actor-critic', 'Actor-Critic', 'Actor-Critic', 'A', '方策と価値関数を同時に学習する強化学習手法。', 2, 'g-kentei'),
    ('adaboost', 'AdaBoost', 'AdaBoost', 'A', '弱学習器を逐次重み付けするブースティング。', 2, 'g-kentei'),
    ('automl', 'AutoML', '自動機械学習', '', '機械学習モデルの設計・学習・評価を自動化する技術。専門知識がなくても高精度なモデルを構築できる。', 2, 'g-kentei'),
    ('catboost', 'CatBoost', 'CatBoost', 'C', 'カテゴリ変数に強い勾配ブースティングライブラリ。', 2, 'g-kentei'),
    ('dbscan', 'DBSCAN', 'DBSCAN', 'D', '密度に基づき任意形状クラスタを検出する手法。', 2, 'g-kentei'),
    ('dqn', 'DQN', 'Deep Q-Network', 'D', '深層ネットでQ関数を近似する強化学習。', 2, 'g-kentei'),
    ('extra-trees', 'Extra Trees', 'Extra Trees', 'E', 'ランダム性を高めたアンサンブル木モデル。', 2, 'g-kentei'),
    ('f1-score', 'F1スコア', 'F1 Score', 'F', '適合率と再現率の調和平均。バランス指標として使われる。', 2, 'g-kentei'),
    ('gpu', 'GPU', 'Graphics Processing Unit', 'G', '並列演算に強いプロセッサ。深層学習の学習・推論に広く使われる。', 2, 'g-kentei'),
    ('human-in-the-loop', 'Human-in-the-Loop', 'Human-in-the-Loop', 'H', '人が学習・運用のループに介在し品質や安全性を高める設計。', 2, 'g-kentei|genai-passport'),
    ('iot', 'IoT', 'Internet of Things', 'I', 'センサー付きデバイスがネットワーク接続する仕組み。AIのデータ源。', 2, 'g-kentei'),
    ('isolation-forest', 'Isolation Forest', 'Isolation Forest', 'I', 'ランダム分割で異常点を孤立させ検出する手法。', 2, 'g-kentei'),
    ('l1-regularization', 'L1正則化', 'L1 Regularization', 'L', '重みの絶対値和を罰しスパース解を促す正則化。', 2, 'g-kentei'),
    ('l2-regularization', 'L2正則化', 'L2 Regularization', 'L', '重みの二乗和を罰す正則化。リッジ回帰でも用いる。', 2, 'g-kentei'),
    ('lime', 'LIME', 'LIME', 'L', '局所的に単純モデルで予測を説明する手法。', 2, 'g-kentei'),
    ('lasso-regression', 'Lasso回帰', 'Lasso Regression', 'L', 'L1正則化付き線形回帰。特徴選択効果がある。', 2, 'g-kentei'),
    ('lightgbm', 'LightGBM', 'LightGBM', 'L', '大規模データ向けの高速勾配ブースティングライブラリ。', 2, 'g-kentei'),
    ('ndcg', 'NDCG', 'Normalized Discounted Cumulative Gain', 'N', '正解アイテムが上位にあるほど高いランキング指標。', 2, 'g-kentei'),
    ('np-complete', 'NP完全', 'NP-complete', 'N', 'NPクラスで最も難しい問題クラス。', 2, 'g-kentei'),
    ('numpy', 'NumPy', 'NumPy', 'N', '数値配列計算の基盤Pythonライブラリ。', 2, 'g-kentei'),
    ('overfitting', 'Over-fitting', '過学習', '', '訓練データに適合しすぎて未知のデータへの精度が落ちる現象。ドロップアウトや正則化で対策する。', 2, 'g-kentei'),
    ('platt-scaling', 'Plattスケーリング', 'Platt Scaling', 'P', 'SVM等のスコアを確率に変換する手法。', 2, 'g-kentei'),
    ('prophet', 'Prophet', 'Prophet', 'P', 'Meta製の時系列予測ライブラリ。トレンド・季節性を扱いやすい。', 2, 'g-kentei'),
    ('p-vs-np', 'P対NP問題', 'P vs NP', 'P', '多項式時間で検証と解法が等価かという未解決問題。', 3, 'g-kentei'),
    ('q-learning', 'Q学習', 'Q-learning', 'Q', '行動価値関数を反復更新する代表的強化学習アルゴリズム。', 2, 'g-kentei'),
    ('roc-curve', 'ROC曲線', 'ROC Curve', 'R', '閾値変化に伴う真陽性率と偽陽性率の関係を示す曲線。', 2, 'g-kentei'),
    ('shap', 'SHAP', 'SHAP', 'S', '各特徴の予測への寄与を公平に配分する説明手法。', 2, 'g-kentei'),
    ('smote', 'SMOTE', 'SMOTE', 'S', '少数クラスを合成サンプルで増やす不均衡対策。', 2, 'g-kentei'),
    ('tpu', 'TPU', 'Tensor Processing Unit', 'T', 'Googleが開発した深層学習向けASIC。', 2, 'g-kentei'),
    ('xgboost', 'XGBoost', 'XGBoost', 'X', '高速かつ高精度な勾配ブースティング実装。Kaggleで広く使われる。', 2, 'g-kentei'),
    ('k-means', 'k-means法', 'k-means', 'け', '重心への距離でk個のクラスタに分割する手法。', 2, 'g-kentei'),
    ('k-nearest-neighbors', 'k近傍法', 'k-Nearest Neighbors', 'け', '近傍サンプルの多数決で分類・回帰する非パラメトリック手法。', 2, 'g-kentei'),
    ('pandas', 'pandas', 'pandas', 'p', '表形式データ操作のPythonライブラリ。前処理で広く使われる。', 2, 'g-kentei'),
    ('scikit-learn', 'scikit-learn', 'scikit-learn', 's', 'Pythonの定番機械学習ライブラリ。', 2, 'g-kentei'),
    ('t-sne', 't-SNE', 't-SNE', 't', '非線形次元削減。クラスタ構造の可視化に使われる。', 2, 'g-kentei'),
    ('epsilon-greedy', 'ε-greedy', 'Epsilon-greedy', 'ε', '確率εでランダム行動し探索する単純戦略。', 2, 'g-kentei'),
    ('active-learning', 'アクティブラーニング', 'Active Learning', 'あ', 'ラベル付けすべきデータを能動的に選ぶ学習。', 2, 'g-kentei'),
    ('association-rule', 'アソシエーションルール', 'Association Rule', 'あ', '共起パターンを if-then 形式で抽出する手法。 basket分析など。', 2, 'g-kentei'),
    ('algorithm', 'アルゴリズム', 'Algorithm', '', '問題を解くための手順や計算の流れを定めたもの。AIにおいては学習や推論の方法を指す。', 2, 'g-kentei'),
    ('ensemble-learning', 'アンサンブル学習', 'Ensemble Learning', 'あ', '複数モデルを組み合わせ精度を高める手法群。', 2, 'g-kentei'),
    ('expert-system-shell', 'エキスパートシェル', 'Expert System Shell', 'え', '推論エンジンと知識編集機能を備えた開発環境。', 2, 'g-kentei'),
    ('expert-system', 'エキスパートシステム', 'Expert System', 'え', '専門家の知識をルール化し推論するAIシステム。1980年代に実用化が進んだ。', 2, 'g-kentei'),
    ('edge-ai', 'エッジAI', 'Edge AI', 'え', '端末側で推論を行うAI。低遅延とプライバシー保護に有利。', 2, 'g-kentei'),
    ('epoch', 'エポック', 'Epoch', 'え', '学習データ全体を一通り学習し終えた単位。', 2, 'g-kentei'),
    ('on-device-ai', 'オンデバイスAI', 'On-Device AI', 'お', 'スマートフォン等の端末内で動作するAI推論。', 2, 'g-kentei'),
    ('ontology', 'オントロジー', 'Ontology', 'お', '概念と関係を形式化した知識体系。セマンティックWebや知識グラフの基盤。', 2, 'g-kentei'),
    ('online-learning', 'オンライン学習', 'Online Learning', 'お', 'データが逐次到着するたびにモデルを更新する学習。', 2, 'g-kentei'),
    ('online-anomaly-detection', 'オンライン異常検知', 'Online Anomaly Detection', 'お', 'ストリームデータで逐次異常を検出する。', 2, 'g-kentei'),
    ('kernel-trick', 'カーネルトリック', 'Kernel Trick', 'か', '高次元内積を効率的に計算する技法。', 2, 'g-kentei'),
    ('kernel-method', 'カーネル法', 'Kernel Method', 'か', '高次元特徴空間を暗黙に扱う手法。SVMなどで利用。', 2, 'g-kentei'),
    ('gaussian-mixture', 'ガウス混合モデル', 'Gaussian Mixture Model', 'が', '複数ガウス分布の混合でデータをモデル化する手法。', 2, 'g-kentei'),
    ('calibration', 'キャリブレーション', 'Calibration', 'き', '予測確率が実際の発生率と一致するよう調整すること。', 2, 'g-kentei'),
    ('cloud-ai', 'クラウドAI', 'Cloud AI', 'く', 'クラウド上で提供されるAI APIや学習基盤。', 2, 'g-kentei'),
    ('clustering', 'クラスタリング', 'Clustering', 'く', '類似サンプルをグループ化する教師なし学習。', 2, 'g-kentei'),
    ('clustering-problem', 'クラスタリング問題', 'Clustering Problem', 'く', 'ラベルなしデータを似たグループに分ける教師なし学習の典型。', 2, 'g-kentei'),
    ('class-imbalance', 'クラス不均衡', 'Class Imbalance', 'く', '特定クラスのサンプルが極端に少ないデータ分布。', 2, 'g-kentei'),
    ('graph-based-ml', 'グラフ機械学習', 'Graph-based Machine Learning', 'ぐ', 'グラフ構造データに対する機械学習の総称。', 2, 'g-kentei'),
    ('grid-search', 'グリッドサーチ', 'Grid Search', 'ぐ', 'ハイパーパラメータ候補を総当たり探索する手法。', 2, 'g-kentei'),
    ('game-ai', 'ゲームAI', 'Game AI', 'げ', 'ボードゲームやビデオゲームの対戦・NPC制御に使うAI技術。', 2, 'g-kentei'),
    ('cost-complexity-pruning', 'コスト複雑度剪定', 'Cost-complexity Pruning', 'こ', '決定木の枝を剪定して汎化を高める。', 2, 'g-kentei'),
    ('content-based-filtering', 'コンテンツベースフィルタリング', 'Content-based Filtering', 'こ', 'アイテム属性の類似から推薦する手法。', 2, 'g-kentei'),
    ('support-vector-machine', 'サポートベクターマシン', 'Support Vector Machine', 'さ', 'マージン最大化で分類・回帰を行う古典的強力モデル。', 2, 'g-kentei'),
    ('symbolic-ai', 'シンボリックAI', 'Symbolic AI', 'し', '記号とルールで知識を表現する古典的AIアプローチ。エキスパートシステムの基盤。', 2, 'g-kentei'),
    ('stacking', 'スタッキング', 'Stacking', 'す', 'メタモデルが基底モデルの予測を統合する手法。', 2, 'g-kentei'),
    ('zero-shot-learning', 'ゼロショット学習', 'Zero-shot Learning', 'ぜ', '学習時に見ていないクラスへ一般化する学習設定。', 2, 'g-kentei'),
    ('turing-test', 'チューリングテスト', 'Turing Test', 'ち', '機械が人と区別できない対話ができるかを判定する思考実験。', 2, 'g-kentei'),
    ('turing-machine', 'チューリングマシン', 'Turing Machine', 'ち', '計算可能性の理論モデル。アルゴリズムの限界議論の基礎。', 2, 'g-kentei'),
    ('digital-twin', 'デジタルツイン', 'Digital Twin', 'で', '現実の対象を仮想空間に複製しシミュレーションする技術。', 2, 'g-kentei'),
    ('data-driven', 'データドリブン', 'Data-Driven', 'で', '経験や勘よりデータ分析に基づいて意思決定する考え方。', 2, 'g-kentei'),
    ('data-leakage', 'データリーク', 'Data Leakage', 'で', 'テスト情報が学習に混入し評価が過大になる問題。', 2, 'g-kentei'),
    ('naive-bayes', 'ナイーブベイズ', 'Naive Bayes', 'な', '条件付き独立を仮定した確率的分類器。テキスト分類で定番。', 2, 'g-kentei'),
    ('nested-cross-validation', 'ネストした交差検証', 'Nested Cross-validation', 'ね', 'ハイパーパラメータ選択と評価を分離する検証。', 2, 'g-kentei'),
    ('hyperparameter', 'ハイパーパラメータ', 'Hyperparameter', 'は', '学習前に人が設定するパラメータ。層数や学習率など。', 2, 'g-kentei'),
    ('bias-variance-tradeoff', 'バイアス・バリアンストレードオフ', 'Bias-Variance Tradeoff', 'ば', '単純すぎ・複雑すぎの両極端を避けるモデル設計の考え方。', 2, 'g-kentei'),
    ('bagging', 'バギング', 'Bagging', 'ば', 'データを復元抽出し複数モデルの平均で予測する手法。', 2, 'g-kentei'),
    ('batch-size', 'バッチサイズ', 'Batch Size', 'ば', '一度に処理する学習サンプル数。学習の安定性と速度に影響。', 2, 'g-kentei'),
    ('batch-learning', 'バッチ学習', 'Batch Learning', 'ば', '全データをまとめて学習する従来型の学習方式。', 2, 'g-kentei'),
    ('pipeline', 'パイプライン', 'Pipeline', 'ぱ', '前処理から学習・推論までを連結した処理フロー。', 2, 'g-kentei'),
    ('parameter', 'パラメータ', 'Parameter', 'ぱ', 'モデルが学習で調整する内部変数。重みとバイアスなど。', 2, 'g-kentei'),
    ('perceptron', 'パーセプトロン', 'Perceptron', 'ぱ', '最も単純なニューラルネットワーク素子。線形分離可能問題を学習できる。', 2, 'g-kentei'),
    ('heuristic', 'ヒューリスティック', 'Heuristic', 'ひ', '最適解の保証はないが実用的な解を素早く見つける経験則。', 2, 'g-kentei'),
    ('big-data', 'ビッグデータ', 'Big Data', 'び', '従来手法では扱いきれない規模・多様性のデータ群。', 2, 'g-kentei'),
    ('fuzzy-control', 'ファジィ制御', 'Fuzzy Control', 'ふ', 'ファジィ推論で機器やプロセスを制御する手法。', 2, 'g-kentei'),
    ('fuzzy-logic', 'ファジィ論理', 'Fuzzy Logic', 'ふ', '曖昧さを数学的に扱う論理。ファジィ制御の基盤。', 2, 'g-kentei'),
    ('frame-representation', 'フレーム', 'Frame', 'ふ', 'スロットと値でオブジェクト知識を表現する枠組み。', 2, 'g-kentei'),
    ('boosting', 'ブースティング', 'Boosting', 'ぶ', '誤分類を重視し逐次モデルを追加するアンサンブル。', 2, 'g-kentei'),
    ('production-rule', 'プロダクションルール', 'Production Rule', 'ぷ', 'IF-THEN形式のルールで知識を表現する。', 2, 'g-kentei'),
    ('bayesian-network', 'ベイズネットワーク', 'Bayesian Network', 'べ', '因果・条件付き独立をグラフで表す確率モデル。', 2, 'g-kentei'),
    ('bayesian-inference', 'ベイズ推論', 'Bayesian Inference', 'べ', '事前分布とデータから事後分布を更新する推論枠組み。', 2, 'g-kentei'),
    ('bayesian-optimization', 'ベイズ最適化', 'Bayesian Optimization', 'べ', '少ない試行でハイパーパラメータを効率的に探索。', 2, 'g-kentei'),
    ('baseline-model', 'ベースラインモデル', 'Baseline Model', 'べ', '比較の基準となる単純モデル。改善幅の判断に使う。', 2, 'g-kentei'),
    ('holdout-validation', 'ホールドアウト検証', 'Hold-out Validation', 'ほ', '学習・検証データを一度だけ分割して評価する方法。', 2, 'g-kentei'),
    ('markov-decision-process', 'マルコフ決定過程', 'Markov Decision Process', 'ま', '状態・行動・報酬で強化学習問題を形式化する枠組み。', 2, 'g-kentei'),
    ('markov-chain', 'マルコフ連鎖', 'Markov Chain', 'ま', '次の状態が現在のみに依存する確率過程。', 2, 'g-kentei'),
    ('markov-random-field', 'マルコフ随机场', 'Markov Random Field', 'ま', '画像の画素ラベル付け等に使う無向グラフィカルモデル。', 2, 'g-kentei'),
    ('multi-agent-system', 'マルチエージェントシステム', 'Multi-Agent System', 'ま', '複数の自律エージェントが協調・交渉するシステム。', 2, 'g-kentei'),
    ('multi-task-learning', 'マルチタスク学習', 'Multi-task Learning', 'ま', '複数タスクを同時に学習し表現を共有する手法。', 2, 'g-kentei'),
    ('minimax', 'ミニマックス法', 'Minimax', 'み', '二人零和ゲームで最善手を選ぶ探索手法。チェスAIなどに用いられる。', 2, 'g-kentei'),
    ('meta-learning', 'メタ学習', 'Meta Learning', 'め', '新しいタスクへ素早く適応できるよう学習の仕方を学ぶ手法。', 2, 'g-kentei'),
    ('model', 'モデル', 'Model', 'も', '入力から出力への変換を表す数学的・計算的な表現。', 2, 'g-kentei|genai-passport'),
    ('model-compression', 'モデル圧縮', 'Model Compression', 'も', '剪定・蒸留・量子化などでモデルを小さくする技術群。', 2, 'g-kentei'),
    ('model-evaluation', 'モデル評価', 'Model Evaluation', 'も', '汎化性能やビジネス適合性を測るプロセス全体。', 2, 'g-kentei'),
    ('monte-carlo-tree-search', 'モンテカルロ木探索', 'Monte Carlo Tree Search', 'も', 'ランダムシミュレーションで有望手を評価する探索。囲碁AIで有名。', 2, 'g-kentei'),
    ('label-propagation', 'ラベル伝播', 'Label Propagation', 'ら', 'グラフ上でラベルを近傍に伝播する半教師あり手法。', 2, 'g-kentei'),
    ('ranking-metrics', 'ランキング指標', 'Ranking Metrics', 'ら', '推薦・検索の順位品質を測る指標群。NDCGなど。', 2, 'g-kentei'),
    ('random-search', 'ランダムサーチ', 'Random Search', 'ら', 'ハイパーパラメータをランダムサンプリングする探索。', 2, 'g-kentei'),
    ('random-forest', 'ランダムフォレスト', 'Random Forest', 'ら', '多数の決定木を組み合わせたアンサンブル学習。', 2, 'g-kentei'),
    ('ridge-regression', 'リッジ回帰', 'Ridge Regression', 'り', 'L2正則化付き線形回帰。共線性に比較的強い。', 2, 'g-kentei'),
    ('logistic-regression', 'ロジスティック回帰', 'Logistic Regression', 'ろ', 'シグモイド関数で二値分類を行う線形モデル。', 2, 'g-kentei'),
    ('robotics', 'ロボティクス', 'Robotics', 'ろ', 'ロボットの知覚・判断・行動を統合する工学とAIの融合領域。', 2, 'g-kentei'),
    ('imbalanced-learning', '不均衡学習', 'Imbalanced Learning', 'ふ', 'クラス不均衡データ向けの学習技法の総称。', 2, 'g-kentei'),
    ('pca', '主成分分析', 'Principal Component Analysis', 'し', '分散の大きい方向へ射影する線形次元削減。', 2, 'g-kentei'),
    ('cross-validation', '交差検証', 'Cross Validation', 'こ', 'データを分割し汎化性能を安定評価する手法。', 2, 'g-kentei'),
    ('artificial-intelligence', '人工知能', 'Artificial Intelligence', 'じ', '人間の知能をコンピュータで模倣・実現しようとする技術・研究分野の総称。', 1, 'g-kentei'),
    ('fairness-metrics', '公平性指標', 'Fairness Metrics', 'こ', '属性ごとの性能差を測りバイアスを定量化する指標。', 2, 'g-kentei|genai-passport'),
    ('recall', '再現率', 'Recall', 'さ', '実際の陽性のうち正しく検出できた割合。', 2, 'g-kentei'),
    ('quantile-regression', '分位点回帰', 'Quantile Regression', 'ぶ', '条件付き分位点を推定する回帰手法。', 2, 'g-kentei'),
    ('classification-problem', '分類問題', 'Classification Problem', 'ぶ', '入力を定義済みカテゴリに割り当てる教師あり学習の典型。', 2, 'g-kentei'),
    ('constraint-satisfaction', '制約充足問題', 'Constraint Satisfaction Problem', 'せ', '変数への値割当が制約を満たす問題。', 2, 'g-kentei'),
    ('gradient-boosting', '勾配ブースティング', 'Gradient Boosting', 'こ', '残差を順次学習する強力なアンサンブル枠組み。', 2, 'g-kentei'),
    ('gradient-descent', '勾配降下法', 'Gradient Descent', 'こ', '損失を減らす方向へパラメータを反復更新する最適化の基本手法。', 2, 'g-kentei'),
    ('semi-supervised-learning', '半教師あり学習', 'Semi-supervised Learning', 'は', '少量のラベル付きと大量のラベルなしデータを併用する学習。', 2, 'g-kentei'),
    ('semi-supervised-anomaly', '半教師あり異常検知', 'Semi-supervised Anomaly Detection', 'は', '正常データのみで異常を学習する設定。', 2, 'g-kentei'),
    ('recommender-collaborative', '協調フィルタリング', 'Collaborative Filtering', 'き', 'ユーザー間・アイテム間の類似から推薦する手法。', 2, 'g-kentei'),
    ('co-training', '協調学習', 'Co-training', 'き', '複数ビューで相互に教師データを増やす半教師あり手法。', 2, 'g-kentei'),
    ('monotonic-constraint', '単調制約', 'Monotonic Constraint', 'た', '入力増加で出力も増えるなどの制約をモデルに課す。', 2, 'g-kentei'),
    ('propositional-logic', '命題論理', 'Propositional Logic', 'め', '命題の真偽と論理結合を扱う形式論理。', 2, 'g-kentei'),
    ('regression-problem', '回帰問題', 'Regression Problem', 'か', '連続値を予測する教師あり学習の典型。', 2, 'g-kentei'),
    ('causal-inference', '因果推論', 'Causal Inference', 'い', '相関だけでなく因果効果を推定する統計・MLの領域。', 2, 'g-kentei'),
    ('reward-function', '報酬関数', 'Reward Function', 'ほ', 'エージェントの行動を評価するスカラー信号。', 2, 'g-kentei'),
    ('multi-instance-learning', '多インスタンス学習', 'Multiple Instance Learning', 'た', '袋ラベルのみからインスタンスを学習する設定。', 2, 'g-kentei'),
    ('multi-label-classification', '多ラベル分類', 'Multi-label Classification', 'た', '1サンプルに複数ラベルが付く分類問題。', 2, 'g-kentei'),
    ('multi-armed-bandit', '多腕バンディット', 'Multi-armed Bandit', 'た', '限られた試行で最良選択肢を見つける問題設定。', 2, 'g-kentei'),
    ('training', '学習', 'Training', 'が', 'データからモデルのパラメータを最適化するプロセス。', 2, 'g-kentei|genai-passport'),
    ('learning-to-rank', '学習toランク', 'Learning to Rank', 'が', '検索・推薦の順位付けを直接最適化する学習。', 2, 'g-kentei'),
    ('learning-curve', '学習曲線', 'Learning Curve', 'が', 'データ量やエポックと性能の関係を示す曲線。', 2, 'g-kentei'),
    ('learning-rate', '学習率', 'Learning Rate', 'が', '勾配降下の更新幅を決めるハイパーパラメータ。', 2, 'g-kentei'),
    ('log-loss', '対数損失', 'Log Loss', 'た', '確率予測の質を評価する損失・指標。', 2, 'g-kentei'),
    ('few-shot-learning', '少数ショット学習', 'Few-shot Learning', 'し', 'ごく少数の例から新クラスを認識する学習設定。', 2, 'g-kentei'),
    ('local-search', '局所探索', 'Local Search', 'き', '近傍解を反復改善する最適化手法。', 2, 'g-kentei'),
    ('stratified-k-fold', '層化k分割交差検証', 'Stratified k-fold', 'そ', 'クラス比率を保った交差検証。', 2, 'g-kentei'),
    ('breadth-first-search', '幅優先探索', 'Breadth-First Search', 'は', '浅い深さから順にノードを探索する手法。最短経路の保証がある場合がある。', 2, 'g-kentei'),
    ('mean-squared-error', '平均二乗誤差', 'Mean Squared Error', 'へ', '回帰の予測誤差二乗の平均。外れ値に敏感。', 2, 'g-kentei'),
    ('mean-absolute-error', '平均絶対誤差', 'Mean Absolute Error', 'へ', '回帰の絶対誤差平均。解釈しやすい指標。', 2, 'g-kentei'),
    ('weak-ai', '弱いAI', 'Weak AI / Narrow AI', 'よ', '特定のタスクに特化したAI。現実に稼働する大半のAIはこれに該当する。', 2, 'g-kentei'),
    ('weak-supervision', '弱教師', 'Weak Supervision', 'じ', 'ノイズラベルやルールから弱い教師信号を得る学習。', 2, 'g-kentei'),
    ('strong-ai', '強いAI', 'Strong AI', 'つ', '人間と同等の汎用知能を持つとされるAI。AGIとほぼ同義で未実現。', 2, 'g-kentei'),
    ('reinforcement-learning', '強化学習', 'Reinforcement Learning', '', '報酬を最大化するように行動を学習するAIの手法。ゲームAIやロボット制御に使われる。ChatGPTの改善にも活用された。', 2, 'g-kentei'),
    ('semantic-network-basic', '意味ネットワーク', 'Semantic Network', 'い', '概念をノード・リンクで表す知識表現。', 2, 'g-kentei'),
    ('voting-ensemble', '投票アンサンブル', 'Voting Ensemble', 'と', '複数モデルの多数決・平均で予測する手法。', 2, 'g-kentei'),
    ('exploration-exploitation', '探索と活用', 'Exploration vs Exploitation', 'た', '未知行動を試すか既知の良手を使うかのトレードオフ。', 2, 'g-kentei'),
    ('search-algorithm', '探索アルゴリズム', 'Search Algorithm', 'た', '状態空間から解を見つける手続き。経路探索・ゲーム木探索の基礎。', 2, 'g-kentei'),
    ('recommendation-algorithm', '推薦アルゴリズム', 'Recommendation Algorithm', 'す', 'ユーザー嗜好に合うアイテムを推薦するアルゴリズム群。', 2, 'g-kentei'),
    ('recommendation-system', '推薦システム', 'Recommendation System', 'す', 'ユーザーの嗜好に合う商品・コンテンツを推薦するAIシステム。', 2, 'g-kentei'),
    ('inference', '推論', 'Inference', 'す', '学習済みモデルで新しい入力に対し予測を行う処理。', 2, 'g-kentei|genai-passport'),
    ('inference-engine', '推論エンジン', 'Inference Engine', 'す', 'ルールベース知識から結論を導き出す中核コンポーネント。', 2, 'g-kentei'),
    ('loss-function', '損失関数', 'Loss Function', 'そ', '予測と正解のズレを数値化する関数。学習の最適化目標となる。', 2, 'g-kentei'),
    ('supervised-learning', '教師あり学習', 'Supervised Learning', '', '正解ラベル付きのデータを使って学習する機械学習の手法。画像分類やスパムフィルタリングなどに広く使われる。', 2, 'g-kentei'),
    ('unsupervised-learning', '教師なし学習', 'Unsupervised Learning', '', '正解ラベルなしのデータからパターンを自動的に見つけ出す機械学習の手法。クラスタリングや次元削減に使われる。', 2, 'g-kentei'),
    ('policy-gradient', '方策勾配法', 'Policy Gradient', 'ほ', '方策を直接最適化する強化学習のクラス。', 2, 'g-kentei'),
    ('early-stopping', '早期終了', 'Early Stopping', 'そ', '検証性能が悪化し始めたら学習を打ち切る正則化手法。', 2, 'g-kentei'),
    ('early-stopping-patience', '早期終了の忍耐', 'Early Stopping Patience', 'そ', '検証悪化が続くエポック数の上限設定。', 2, 'g-kentei'),
    ('time-series-forecasting', '時系列予測', 'Time Series Forecasting', 'じ', '過去の時系列から将来値を予測するタスク。', 2, 'g-kentei'),
    ('maximum-likelihood', '最尤推定', 'Maximum Likelihood Estimation', 'さ', '観測データの尤度を最大化するパラメータ推定。', 2, 'g-kentei'),
    ('optimization-problem', '最適化問題', 'Optimization Problem', 'さ', '目的関数を最大または最小にする変数を求める問題設定。', 2, 'g-kentei'),
    ('underfitting', '未学習', 'Underfitting', 'み', 'モデルが単純すぎて訓練データにも適合できない状態。', 2, 'g-kentei'),
    ('concept-drift', '概念ドリフト', 'Concept Drift', 'が', '時間とともにデータ分布や正解の関係が変化する現象。', 2, 'g-kentei'),
    ('imitation-learning', '模倣学習', 'Imitation Learning', 'も', '専門家の行動データから方策を学ぶ手法。', 2, 'g-kentei'),
    ('machine-learning', '機械学習', 'Machine Learning', '', 'データから自動的にパターンを学習し予測・判断を行うAI技術の総称。ディープラーニングは機械学習の一分野。', 2, 'g-kentei'),
    ('dimensionality-reduction', '次元削減', 'Dimensionality Reduction', 'じ', '高次元データを低次元に圧縮し可視化や学習を容易にする。', 2, 'g-kentei'),
    ('regularization', '正則化', 'Regularization', 'せ', 'パラメータの大きさを罰し過学習を抑える技法。', 2, 'g-kentei'),
    ('accuracy', '正解率', 'Accuracy', 'せ', '全体に占める正解の割合。クラス不均衡では誤解を招きやすい。', 2, 'g-kentei'),
    ('r-squared', '決定係数', 'R-squared', 'け', '回帰モデルが説明できる分散の割合。', 2, 'g-kentei'),
    ('decision-tree', '決定木', 'Decision Tree', 'け', 'if-then分岐で予測する解釈しやすいモデル。', 2, 'g-kentei'),
    ('activation-function', '活性化関数', 'Activation Function', 'か', 'ニューロン出力に非線形性を与える関数。ReLUやシグモイドなど。', 2, 'g-kentei'),
    ('depth-first-search', '深さ優先探索', 'Depth-First Search', 'ふ', '一方の枝を深く掘り下げる探索手法。メモリ効率が良い。', 2, 'g-kentei'),
    ('confusion-matrix', '混同行列', 'Confusion Matrix', 'こ', '分類結果の正解・誤判定を表形式で示す評価表。', 2, 'g-kentei'),
    ('temperature-scaling', '温度スケーリング', 'Temperature Scaling', 'お', '予測確率のキャリブレーション手法。', 2, 'g-kentei'),
    ('simulated-annealing', '焼きなまし法', 'Simulated Annealing', 'や', '金属の焼きなましを模した確率的局所探索。', 2, 'g-kentei'),
    ('feature-selection', '特徴選択', 'Feature Selection', 'と', '有用な特徴だけを残し次元やノイズを減らす工程。', 2, 'g-kentei'),
    ('feature-engineering', '特徴量エンジニアリング', 'Feature Engineering', 'と', 'ドメイン知識で入力特徴を設計・変換する作業。', 2, 'g-kentei'),
    ('feature-interaction', '特徴量交互作用', 'Feature Interaction', 'と', '複数特徴の組み合わせ効果をモデル化すること。', 2, 'g-kentei'),
    ('anomaly-detection', '異常検知', 'Anomaly Detection', 'い', '通常と異なるパターンを検出するタスク。不正検知などに利用。', 2, 'g-kentei'),
    ('knowledge-graph', '知識グラフ', 'Knowledge Graph', 'ち', 'エンティティと関係をグラフ構造で表現した知識ベース。検索・推薦に活用。', 2, 'g-kentei'),
    ('knowledge-representation', '知識表現', 'Knowledge Representation', 'ち', 'AIが推論に使えるよう知識を形式化して表す方法論。', 2, 'g-kentei'),
    ('probability-distribution', '確率分布', 'Probability Distribution', 'か', '乱数や事象の起こりやすさを記述する数学的モデル。', 2, 'g-kentei'),
    ('isotonic-regression', '等張回帰', 'Isotonic Regression', 'と', '単調制約付きの非パラメトリック回帰。', 2, 'g-kentei'),
    ('particle-swarm-optimization', '粒子群最適化', 'Particle Swarm Optimization', 'り', '粒子の集団が最適解へ移動する最適化手法。', 2, 'g-kentei'),
    ('linear-regression', '線形回帰', 'Linear Regression', 'せ', '説明変数の線形結合で連続値を予測する基本モデル。', 2, 'g-kentei'),
    ('swarm-intelligence', '群知能', 'Swarm Intelligence', 'ぐ', '蟻コロニーなど分散主体の協調的知能。', 2, 'g-kentei'),
    ('autonomous-driving', '自動運転', 'Autonomous Driving', 'じ', 'センサーとAIで車両を自律走行させる技術。', 2, 'g-kentei'),
    ('ant-colony-optimization', '蟻コロニー最適化', 'Ant Colony Optimization', 'あ', 'フェロモンで経路探索を行うメタヒューリスティック。', 2, 'g-kentei'),
    ('matrix-factorization', '行列分解', 'Matrix Factorization', 'ぎ', '評価行列を低ランク近似し潜在因子を学習する推薦手法。', 2, 'g-kentei'),
    ('computability', '計算可能性', 'Computability', 'け', '問題がアルゴリズムで解けるかという理論的性質。', 2, 'g-kentei'),
    ('train-test-split', '訓練・テスト分割', 'Train-Test Split', 'く', '未知データ性能を見るためデータを学習用と評価用に分ける。', 2, 'g-kentei'),
    ('backpropagation', '誤差逆伝播法', 'Backpropagation', 'ご', '損失の勾配を層ごとに逆方向へ伝播し重みを更新する学習法。', 1, 'g-kentei'),
    ('explainable-ai', '説明可能なAI', 'Explainable AI / XAI', 'せ', 'AIの判断根拠を人が理解できる形で示す研究・要件。', 2, 'g-kentei|genai-passport'),
    ('negative-sampling', '負例サンプリング', 'Negative Sampling', 'ふ', '対照学習や埋め込みで負例を効率的に選ぶ手法。', 2, 'g-kentei'),
    ('transfer-learning', '転移学習', 'Transfer Learning', '', 'あるタスクで学習済みのモデルを別のタスクに応用する手法。少ないデータでも高い精度を実現できる。', 2, 'g-kentei'),
    ('predicate-logic', '述語論理', 'Predicate Logic', 'じ', '述語と量詞で関係を表現する論理。', 2, 'g-kentei'),
    ('federated-learning', '連合学習', 'Federated Learning', 'れ', 'データを集約せず端末分散で協調学習する枠組み。', 2, 'g-kentei'),
    ('precision', '適合率', 'Precision', 'て', '陽性予測のうち実際に陽性だった割合。', 2, 'g-kentei'),
    ('genetic-algorithm', '遺伝的アルゴリズム', 'Genetic Algorithm', 'い', '選択・交叉・突然変異で解を進化させる手法。', 2, 'g-kentei'),
    ('partial-dependence', '部分依存プロット', 'Partial Dependence Plot', 'ぶ', '特定特徴と予測の平均的関係を可視化する手法。', 2, 'g-kentei'),
    ('quantization', '量子化', 'Quantization', 'り', 'モデルの数値精度を下げて軽量化・高速化する技法。', 2, 'g-kentei'),
    ('hierarchical-clustering', '階層的クラスタリング', 'Hierarchical Clustering', 'か', '樹形図でクラスタの包含関係を表す手法。', 2, 'g-kentei'),
    ('hidden-markov-model', '隠れマルコフモデル', 'Hidden Markov Model', 'か', '観測できない状態系列を仮定する確率モデル。', 2, 'g-kentei'),
    ('speech-synthesis', '音声合成', 'Speech Synthesis', 'お', 'テキストから人間らしい音声を生成する技術。', 2, 'g-kentei'),
    ('speech-recognition', '音声認識', 'Speech Recognition', 'お', '音声信号をテキストなどに変換する技術。アシスタントの入口。', 2, 'g-kentei'),
    ('permutation-importance', '順列重要度', 'Permutation Importance', 'じ', '特徴をシャッフルし性能低下から重要度を測る手法。', 2, 'g-kentei'),
    ('ordinal-classification', '順序分類', 'Ordinal Classification', 'じ', 'クラス間に順序がある分類問題。', 2, 'g-kentei'),
]
