"""案B: データ・運用（101語）。"""

# id, name, yomi, reading, summary, tier, exams
TERMS = [
    ('apache-spark', 'Apache Spark', 'Apache Spark', 'A', '大規模データの分散処理フレームワーク。', 2, 'g-kentei'),
    ('chroma', 'Chroma', 'Chroma', 'C', 'LLMアプリ向けのオープンソースベクトルDB。', 2, 'g-kentei'),
    ('dvc', 'DVC', 'Data Version Control', 'D', 'ML向けデータ・実験のバージョン管理ツール。', 2, 'g-kentei'),
    ('elt', 'ELT', 'Extract Load Transform', 'E', 'まず格納し後から変換するデータ統合方式。', 2, 'g-kentei'),
    ('etl', 'ETL', 'Extract Transform Load', 'E', 'データ抽出・変換・格納の一連パイプライン。', 2, 'g-kentei'),
    ('elasticsearch', 'Elasticsearch', 'Elasticsearch', 'E', '全文検索・分析に強い分散検索エンジン。', 2, 'g-kentei'),
    ('faiss', 'FAISS', 'FAISS', 'F', 'Meta製の高速ベクトル検索ライブラリ。', 2, 'g-kentei'),
    ('hnsw', 'HNSW', 'Hierarchical Navigable Small World', 'H', 'ベクトル検索で広く使われるグラフベース索引。', 2, 'g-kentei'),
    ('jupyter-notebook', 'Jupyter Notebook', 'Jupyter Notebook', 'J', 'コード・可視化・説明を一つのノートで実行できる環境。', 2, 'g-kentei'),
    ('mlops', 'MLOps', 'MLOps', 'M', '機械学習の開発・デプロイ・監視を継続的に回す運用体制。', 2, 'g-kentei'),
    ('matplotlib', 'Matplotlib', 'Matplotlib', 'M', 'Pythonの基本グラフ描画ライブラリ。', 2, 'g-kentei'),
    ('nosql', 'NoSQL', 'NoSQL', 'N', '非リレーショナルなデータベースの総称。', 2, 'g-kentei'),
    ('pinecone', 'Pinecone', 'Pinecone', 'P', 'マネージドベクトルデータベースサービス。', 2, 'g-kentei'),
    ('sql', 'SQL', 'Structured Query Language', 'S', 'リレーショナルデータベースを操作する言語。', 2, 'g-kentei'),
    ('seaborn', 'Seaborn', 'Seaborn', 'S', '統計グラフを簡単に描くPythonライブラリ。', 2, 'g-kentei'),
    ('weaviate', 'Weaviate', 'Weaviate', 'W', 'ベクトル検索とオブジェクト保存を統合したDB。', 2, 'g-kentei'),
    ('p-value', 'p値', 'p-value', 'p', '観測結果が偶然で起きる確率の指標。', 2, 'g-kentei'),
    ('annotation-guideline', 'アノテーションガイドライン', 'Annotation Guideline', 'あ', 'ラベル付けの基準を文書化した手順書。', 2, 'g-kentei'),
    ('index-database', 'インデックス', 'Database Index', 'い', '検索を高速化するデータベースの索引構造。', 2, 'g-kentei'),
    ('online-offline-features', 'オンライン・オフライン特徴', 'Online Offline Features', 'お', 'リアルタイム推論用と学習用の特徴の使い分け。', 2, 'g-kentei'),
    ('canary-release', 'カナリアリリース', 'Canary Release', 'か', '一部ユーザーだけ新モデルへ段階的に切替。', 2, 'g-kentei'),
    ('crowdsourcing-label', 'クラウドソーシングラベル', 'Crowdsourced Labeling', 'く', '多数の作業者でデータにラベルを付与する方式。', 2, 'g-kentei'),
    ('class-label', 'クラスラベル', 'Class Label', 'く', '分類タスクのカテゴリ名・ID。', 2, 'g-kentei'),
    ('class-weight', 'クラス重み', 'Class Weight', 'く', '不均衡クラスに異なる損失重みを付ける。', 2, 'g-kentei'),
    ('sampling', 'サンプリング', 'Sampling', 'さ', '母集団から部分データを選び取る統計的手法。', 2, 'g-kentei'),
    ('sample-weight', 'サンプル重み', 'Sample Weight', 'さ', '各サンプルに学習上の重みを付与する。', 2, 'g-kentei'),
    ('shadow-deployment', 'シャドーデプロイ', 'Shadow Deployment', 'し', '本番トラフィックのコピーで新モデルを並行検証。', 2, 'g-kentei'),
    ('schema', 'スキーマ', 'Schema', 'す', 'データ構造の定義。列名・型・制約など。', 2, 'g-kentei'),
    ('schema-evolution', 'スキーマ進化', 'Schema Evolution', 'す', '時間とともにデータ構造が変化することへの対応。', 2, 'g-kentei'),
    ('data-warehouse', 'データウェアハウス', 'Data Warehouse', 'で', '分析向けに整理された統合データ基盤。', 2, 'g-kentei'),
    ('data-catalog', 'データカタログ', 'Data Catalog', 'で', '組織内データ資産を検索・管理する目録。', 2, 'g-kentei'),
    ('data-catalog-search', 'データカタログ検索', 'Data Catalog Search', 'で', '組織内データ資産を検索・発見する機能。', 2, 'g-kentei'),
    ('data-governance', 'データガバナンス', 'Data Governance', 'で', 'データの品質・セキュリティ・利用規則を統制する。', 2, 'g-kentei'),
    ('data-cleaning', 'データクレンジング', 'Data Cleaning', 'で', '誤り・重複・不整合を除去し品質を高める作業。', 2, 'g-kentei'),
    ('data-contract', 'データコントラクト', 'Data Contract', 'で', 'データ提供者と利用者の品質・スキーマ合意。', 2, 'g-kentei'),
    ('dataset', 'データセット', 'Dataset', '', 'AIの学習に使う大量のデータをまとめたもの。データの質と量がモデルの性能を大きく左右する。', 2, 'g-kentei'),
    ('data-drift-detection', 'データドリフト検知', 'Data Drift Detection', 'で', '入力分布の変化を監視しモデル劣化を早期検知。', 2, 'g-kentei'),
    ('data-versioning', 'データバージョン管理', 'Data Versioning', 'で', 'データセットの版を記録し再現性を確保する。', 2, 'g-kentei'),
    ('data-pipeline', 'データパイプライン', 'Data Pipeline', 'で', 'データ収集から利用までの自動化フロー。', 2, 'g-kentei'),
    ('data-product', 'データプロダクト', 'Data Product', 'で', '再利用可能な形で提供されるデータ資産。', 2, 'g-kentei'),
    ('data-profiling', 'データプロファイリング', 'Data Profiling', 'で', 'データの分布・欠損・型を調査・要約する。', 2, 'g-kentei'),
    ('data-mesh', 'データメッシュ', 'Data Mesh', 'で', 'ドメイン単位でデータ所有権を分散する設計思想。', 2, 'g-kentei'),
    ('data-lake', 'データレイク', 'Data Lake', 'で', '生データを大量に蓄積するストレージ基盤。', 2, 'g-kentei'),
    ('data-retention', 'データ保持期間', 'Data Retention', 'で', 'データを保管する期間と削除ポリシー。', 2, 'g-kentei|genai-passport'),
    ('data-preprocessing', 'データ前処理', 'Data Preprocessing', 'で', '学習前に欠損・外れ値・形式を整える工程。', 2, 'g-kentei'),
    ('data-anonymization', 'データ匿名化', 'Data Anonymization', 'で', '個人を特定できないようデータを加工する。', 2, 'g-kentei|genai-passport'),
    ('visualization', 'データ可視化', 'Data Visualization', 'で', 'グラフや図でデータの傾向を伝える技法。', 2, 'g-kentei'),
    ('data-quality', 'データ品質', 'Data Quality', 'で', '正確性・完全性・一貫性などデータの信頼性。', 2, 'g-kentei'),
    ('data-lineage', 'データ系譜', 'Data Lineage', 'で', 'データの出所と変換履歴を追跡可能にすること。', 2, 'g-kentei'),
    ('histogram', 'ヒストグラム', 'Histogram', 'ひ', '値の分布を区間ごとの頻度で示すグラフ。', 2, 'g-kentei'),
    ('heatmap', 'ヒートマップ', 'Heatmap', 'ひ', '行列値を色の濃淡で表す可視化。', 2, 'g-kentei'),
    ('feature-store', 'フィーチャストア', 'Feature Store', 'ふ', '学習・推論で共通利用する特徴量を管理する基盤。', 2, 'g-kentei'),
    ('feature-platform', 'フィーチャープラットフォーム', 'Feature Platform', 'ふ', '特徴量の定義・生成・提供を一元化する基盤。', 2, 'g-kentei'),
    ('privacy-preserving-ml', 'プライバシー保護ML', 'Privacy-preserving ML', 'ぷ', '個人情報を守りながら学習・分析する技術群。', 2, 'g-kentei'),
    ('vector-index', 'ベクトルインデックス', 'Vector Index', 'べ', '高次元ベクトルの近似最近傍検索を高速化する索引。', 2, 'g-kentei'),
    ('vector-database', 'ベクトルデータベース', 'Vector Database', '', 'テキストや画像をベクトル（数値の配列）として保存・検索するデータベース。RAGシステムの構築に欠かせない。', 2, 'g-kentei'),
    ('metadata', 'メタデータ', 'Metadata', 'め', 'データについてのデータ。スキーマ・出所・更新日など。', 2, 'g-kentei'),
    ('model-drift', 'モデルドリフト', 'Model Drift', 'も', '運用中にモデル性能が徐々に劣化する現象。', 2, 'g-kentei'),
    ('model-registry', 'モデルレジストリ', 'Model Registry', 'も', '学習済みモデルの版管理と承認フローを担う仕組み。', 2, 'g-kentei'),
    ('model-artifact', 'モデル成果物', 'Model Artifact', 'も', '学習済み重み・設定・前処理をまとめた成果物。', 2, 'g-kentei'),
    ('model-monitoring', 'モデル監視', 'Model Monitoring', 'も', '本番モデルの性能・データ品質を継続監視する。', 2, 'g-kentei'),
    ('label', 'ラベル', 'Label', 'ら', '教師あり学習の正解情報。', 2, 'g-kentei'),
    ('label-encoding', 'ラベルエンコーディング', 'Label Encoding', 'ら', 'カテゴリに整数IDを割り当てる符号化。', 2, 'g-kentei'),
    ('label-drift', 'ラベルドリフト', 'Label Drift', 'ら', '正解ラベルの分布や意味が変化する現象。', 2, 'g-kentei'),
    ('label-noise', 'ラベルノイズ', 'Label Noise', 'ら', '誤ったラベルが学習データに混ざる問題。', 2, 'g-kentei'),
    ('relational-database', 'リレーショナルDB', 'Relational Database', 'り', '表と関係でデータを管理するデータベース。', 2, 'g-kentei'),
    ('one-hot-encoding', 'ワンホットエンコーディング', 'One-hot Encoding', 'わ', 'カテゴリ変数を0/1ベクトルで表現する。', 2, 'g-kentei'),
    ('random-seed', '乱数シード', 'Random Seed', 'ら', '乱数生成の初期値。実験の再現性に必須。', 2, 'g-kentei'),
    ('pseudonymization-data', '仮名化処理', 'Pseudonymization', 'か', '識別子を置換し再識別リスクを下げる加工。', 2, 'g-kentei'),
    ('hypothesis-testing', '仮説検定', 'Hypothesis Testing', 'か', '帰無仮説の棄却可否を統計的に判断する手法。', 2, 'g-kentei'),
    ('confidence-interval', '信頼区間', 'Confidence Interval', 'し', '真の値が含まれる可能性の高い区間推定。', 2, 'g-kentei'),
    ('reproducibility', '再現性', 'Reproducibility', 'さ', '同じ手順で同じ結果が得られる性質。', 2, 'g-kentei'),
    ('semi-structured-data', '半構造化データ', 'Semi-structured Data', 'は', 'JSONやログなど一定の構造を持つ非表形式データ。', 2, 'g-kentei'),
    ('synthetic-tabular-data', '合成表データ', 'Synthetic Tabular Data', 'ご', '生成モデルで作ったプライバシー配慮の表データ。', 2, 'g-kentei'),
    ('causation', '因果関係', 'Causation', 'い', '一方の変化が他方の変化を引き起こす関係。', 2, 'g-kentei'),
    ('outlier', '外れ値', 'Outlier', 'は', '他と大きく異なる観測値。ノイズや重要シグナルの可能性。', 2, 'g-kentei'),
    ('train-validation-test', '学習・検証・テスト', 'Train Validation Test Split', 'が', 'データを3分割し学習・調整・最終評価に使う。', 2, 'g-kentei'),
    ('experiment-tracking', '実験管理', 'Experiment Tracking', 'じ', 'パラメータ・指標・成果物を記録する運用。', 2, 'g-kentei'),
    ('stratified-sampling', '層化サンプリング', 'Stratified Sampling', 'そ', '各層の比率を保ちながらサンプルを抽出する。', 2, 'g-kentei'),
    ('exploratory-data-analysis', '探索的データ分析', 'Exploratory Data Analysis', 'た', '可視化と統計でデータの性質を把握する分析。', 2, 'g-kentei'),
    ('inferential-statistics', '推測統計', 'Inferential Statistics', 'す', '標本から母集団の性質を推測する統計。', 2, 'g-kentei'),
    ('inference-log', '推論ログ', 'Inference Log', 'す', '本番推論の入出力・レイテンシを記録したログ。', 2, 'g-kentei'),
    ('scatter-plot', '散布図', 'Scatter Plot', 'さ', '2変数の関係を点で示すグラフ。', 2, 'g-kentei'),
    ('time-series-data', '時系列データ', 'Time Series Data', 'じ', '時間順に観測されたデータ系列。', 2, 'g-kentei'),
    ('structured-data', '構造化データ', 'Structured Data', 'こ', '表形式などスキーマが明確なデータ。', 2, 'g-kentei'),
    ('standardization', '標準化', 'Standardization', 'ひ', '平均0・分散1に変換する前処理。', 2, 'g-kentei'),
    ('missing-value', '欠損値', 'Missing Value', 'け', 'データセットで値が空の項目。補完や削除が必要。', 2, 'g-kentei'),
    ('imputation', '欠損値補完', 'Imputation', 'け', '欠損箇所を推定値で埋める手法。', 2, 'g-kentei'),
    ('normalization', '正規化', 'Normalization', 'せ', '数値スケールを統一する前処理。Min-Max等。', 2, 'g-kentei'),
    ('ground-truth', '正解データ', 'Ground Truth', 'せ', '評価や学習の基準となる正しいラベル・値。', 2, 'g-kentei'),
    ('feature', '特徴量', 'Feature', 'と', 'モデルへの入力となる変数・属性。', 2, 'g-kentei'),
    ('feature-scaling', '特徴量スケーリング', 'Feature Scaling', 'と', '特徴の大きさを揃え学習を安定させる前処理。', 2, 'g-kentei'),
    ('feature-drift', '特徴量ドリフト', 'Feature Drift', 'と', '入力特徴の分布が時間とともに変化する現象。', 2, 'g-kentei'),
    ('spurious-correlation', '疑似相関', 'Spurious Correlation', 'ぎ', '因果なしに見える統計的相関。', 2, 'g-kentei'),
    ('target-variable', '目的変数', 'Target Variable', 'も', '予測対象となる変数。ラベルとも呼ぶ。', 2, 'g-kentei'),
    ('correlation', '相関', 'Correlation', 'そ', '2変数がどれだけ一緒に変化するかの関係。', 2, 'g-kentei'),
    ('box-plot', '箱ひげ図', 'Box Plot', 'は', '中央値・四分位・外れ値を一目で示す図。', 2, 'g-kentei'),
    ('feature-engineering-tabular', '表データ特徴量', 'Tabular Feature Engineering', 'ひ', '集計・エンコード・交互作用など表形式向け特徴設計。', 2, 'g-kentei'),
    ('tabular-data', '表形式データ', 'Tabular Data', 'ひ', '行と列で表される典型的なビジネスデータ。', 2, 'g-kentei'),
    ('descriptive-statistics', '記述統計', 'Descriptive Statistics', 'き', '平均・分散などデータの要約統計量。', 2, 'g-kentei'),
    ('unstructured-data', '非構造化データ', 'Unstructured Data', 'ひ', 'テキスト・画像・音声など形式が自由なデータ。', 2, 'g-kentei'),
]
