"""案B: 生成AI活用（118語）。"""

# id, name, yomi, reading, summary, tier, exams
TERMS = [
    ('agent', 'AIエージェント', 'AI Agent', 'A', '目標達成のためツールや推論を自律的に繰り返すAI。', 1, 'g-kentei|genai-passport'),
    ('ai-literacy', 'AIリテラシー', 'AI Literacy', 'A', 'AIを適切に理解し活用するための基礎素養。', 1, 'g-kentei|genai-passport'),
    ('ai-safety', 'AI安全性', 'AI Safety', 'A', 'AIの誤用・暴走・有害出力を防ぐ研究・実践。', 1, 'g-kentei|genai-passport'),
    ('ai-detector', 'AI生成検出', 'AI-generated Content Detection', 'A', 'コンテンツがAI生成かどうかを判定する技術。', 2, 'g-kentei|genai-passport'),
    ('image-editing-ai', 'AI画像編集', 'AI Image Editing', 'A', '生成モデルで画像の一部を指示に従い変更する。', 2, 'g-kentei|genai-passport'),
    ('watermarking-ai', 'AI透かし', 'AI Watermarking', 'A', 'AI生成物であることを示す埋め込み技術。', 2, 'g-kentei|genai-passport'),
    ('api-key', 'APIキー', 'API Key', 'A', 'AIサービス利用を認証する秘密鍵。', 2, 'g-kentei|genai-passport'),
    ('amazon-bedrock', 'Amazon Bedrock', 'Amazon Bedrock', 'A', 'AWSの基盤モデル提供マネージドサービス。', 2, 'g-kentei'),
    ('autogpt', 'AutoGPT', 'AutoGPT', 'A', '自律的に目標分解・実行するエージェントの代表例。', 2, 'g-kentei'),
    ('cpu-inference', 'CPU推論', 'CPU Inference', 'C', 'CPUのみで行う推論。小規模モデルやエッジ向け。', 2, 'g-kentei'),
    ('chain-of-thought', 'Chain-of-Thought', 'Chain-of-Thought', 'C', '段階的推論を促すプロンプト技法。CoTと略される。', 1, 'g-kentei|genai-passport'),
    ('gpu-inference', 'GPU推論', 'GPU Inference', 'G', 'GPUを使った高速推論。', 2, 'g-kentei'),
    ('json-mode', 'JSONモード', 'JSON Mode', 'J', 'モデルにJSON形式での出力を強制する機能。', 2, 'g-kentei|genai-passport'),
    ('llm-as-judge', 'LLM-as-a-Judge', 'LLM-as-a-Judge', 'L', '別のLLMで回答品質を採点する評価手法。', 2, 'g-kentei|genai-passport'),
    ('langchain', 'LangChain', 'LangChain', 'L', 'LLMアプリ構築のためのチェーン・エージェントフレームワーク。', 2, 'g-kentei|genai-passport'),
    ('rag', 'RAG', 'Retrieval-Augmented Generation', '', '外部の知識データベースを検索しながら回答を生成する手法。幻覚（ハルシネーション）を減らし、最新情報に基づいた回答が可能になる。', 2, 'g-kentei'),
    ('react-pattern', 'ReAct', 'ReAct', 'R', '推論と行動を交互に行うエージェントフレームワーク。', 2, 'g-kentei'),
    ('reflexion', 'Reflexion', 'Reflexion', 'R', '失敗から言語的フィードバックでエージェントを改善。', 2, 'g-kentei'),
    ('top-k', 'Top-k', 'Top-k Sampling', 'T', '確率上位k語からサンプリングする生成設定。', 2, 'g-kentei|genai-passport'),
    ('top-p', 'Top-p', 'Top-p / Nucleus Sampling', 'T', '累積確率pまでの語からサンプリングする生成設定。', 2, 'g-kentei|genai-passport'),
    ('google-vertex-ai', 'Vertex AI', 'Vertex AI', 'V', 'Google Cloudの機械学習・生成AIプラットフォーム。', 2, 'g-kentei'),
    ('outpainting', 'アウトペインティング', 'Outpainting', 'あ', '画像の外側を拡張生成する技法。', 2, 'g-kentei'),
    ('inpainting', 'インペインティング', 'Inpainting', 'い', '画像の欠損部分を周囲から補完生成する技法。', 2, 'g-kentei|genai-passport'),
    ('on-premise-llm', 'オンプレミスLLM', 'On-premise LLM', 'お', '自社環境でホスト・運用する大規模言語モデル。', 2, 'g-kentei|genai-passport'),
    ('guardrails', 'ガードレール', 'Guardrails', 'が', '生成AIの出力を安全範囲に保つ制御・フィルタ。', 2, 'g-kentei|genai-passport'),
    ('grounding', 'グラウンディング', 'Grounding', 'ぐ', '生成内容を外部事実や入力に根拠づけること。', 2, 'g-kentei|genai-passport'),
    ('context-compression', 'コンテキスト圧縮', 'Context Compression', 'こ', '長文履歴を要約・抽出してコンテキスト枠に収める。', 2, 'g-kentei'),
    ('context-length', 'コンテキスト長', 'Context Length', 'こ', 'モデルが扱える入力＋出力のトークン合計上限。', 2, 'g-kentei|genai-passport'),
    ('content-filter', 'コンテンツフィルタ', 'Content Filter', 'こ', '有害・不適切コンテンツを検出・ブロックする仕組み。', 2, 'g-kentei|genai-passport'),
    ('code-interpreter', 'コードインタプリタ', 'Code Interpreter', 'こ', 'LLMがコードを実行し結果を利用する機能。', 2, 'g-kentei|genai-passport'),
    ('code-generation', 'コード生成', 'Code Generation', 'こ', '自然言語指示からプログラムを生成するAI活用。', 2, 'g-kentei|genai-passport'),
    ('system-prompt', 'システムプロンプト', 'System Prompt', 'し', 'モデルの振る舞いを規定する上位指示文。', 1, 'g-kentei|genai-passport'),
    ('shadow-ai', 'シャドーAI', 'Shadow AI', 'し', '社内承認なしに従業員が使う生成AIのこと。', 2, 'g-kentei|genai-passport'),
    ('jailbreak', 'ジェイルブレイク', 'Jailbreak', 'じ', '安全制限を回避して有害出力を引き出す試み。', 1, 'g-kentei|genai-passport'),
    ('jailbreak-defense', 'ジェイルブレイク対策', 'Jailbreak Defense', 'じ', '安全制限回避攻撃を防ぐプロンプト・モデル対策。', 2, 'g-kentei|genai-passport'),
    ('style-transfer', 'スタイル転送', 'Style Transfer', 'す', 'ある画像の画風を別画像に適用する技術。', 2, 'g-kentei'),
    ('streaming-generation', 'ストリーミング生成', 'Streaming Generation', 'す', 'トークンを逐次返し体感速度を高める出力方式。', 2, 'g-kentei|genai-passport'),
    ('sliding-window', 'スライディングウィンドウ', 'Sliding Window', 'す', '長文を分割しながら文脈を維持する処理技法。', 2, 'g-kentei'),
    ('semantic-search', 'セマンティック検索', 'Semantic Search', 'せ', '意味的類似性に基づく検索。', 2, 'g-kentei|genai-passport'),
    ('safety-filter', 'セーフティフィルタ', 'Safety Filter', 'せ', '有害出力を検出・抑制するフィルタ層・後処理。', 2, 'g-kentei|genai-passport'),
    ('zero-shot-prompting', 'ゼロショットプロンプト', 'Zero-shot Prompting', 'ぜ', '例示なしでタスクを指示するプロンプト手法。', 2, 'g-kentei|genai-passport'),
    ('decomposition-prompting', 'タスク分解プロンプト', 'Decomposition Prompting', 'た', '複雑タスクを小タスクに分けて順に解かせる技法。', 2, 'g-kentei|genai-passport'),
    ('chat-template', 'チャットテンプレート', 'Chat Template', 'ち', 'モデル固有の会話フォーマットを定義するテンプレート。', 2, 'g-kentei|genai-passport'),
    ('chunking', 'チャンキング', 'Chunking', 'ち', '長文を検索・生成向けに適切な塊へ分割すること。', 2, 'g-kentei|genai-passport'),
    ('tool-use', 'ツール利用', 'Tool Use', 'つ', 'LLMが外部APIや関数を呼び出してタスクを遂行すること。', 2, 'g-kentei|genai-passport'),
    ('text-to-video', 'テキスト動画生成', 'Text-to-Video', 'て', 'テキストや画像から動画クリップを生成する技術。', 2, 'g-kentei|genai-passport'),
    ('text-to-image', 'テキスト画像生成', 'Text-to-Image', 'て', 'テキスト指示から画像を生成する生成AIタスク。', 1, 'g-kentei|genai-passport'),
    ('text-to-speech-genai', 'テキスト音声合成', 'Text-to-Speech', 'て', 'テキストから自然な音声を生成する技術。', 2, 'g-kentei|genai-passport'),
    ('deepfake', 'ディープフェイク', 'Deepfake', 'で', 'AIで作られた偽の顔・音声・映像。', 1, 'g-kentei|genai-passport'),
    ('data-card', 'データカード', 'Data Card', 'で', '学習データの出所・偏り・制約を記述した文書。', 2, 'g-kentei'),
    ('data-flywheel', 'データフライホイール', 'Data Flywheel', 'で', '利用データが製品改善を回し続ける好循環構造。', 2, 'g-kentei'),
    ('token', 'トークン', 'Token', 'と', 'LLMが処理するテキストの最小単位。', 1, 'g-kentei|genai-passport'),
    ('token-limit', 'トークン上限', 'Token Limit', 'と', '入力・出力で使えるトークン数の制限。', 2, 'g-kentei|genai-passport'),
    ('token-pricing', 'トークン課金', 'Token Pricing', 'と', '入出力トークン数に応じた従量課金モデル。', 2, 'g-kentei|genai-passport'),
    ('knowledge-base', 'ナレッジベース', 'Knowledge Base', 'な', 'RAG等で参照する構造化・非構造化知識の集合。', 2, 'g-kentei|genai-passport'),
    ('negative-prompt', 'ネガティブプロンプト', 'Negative Prompt', 'ね', '生成してほしくない要素を指定する指示。', 2, 'g-kentei|genai-passport'),
    ('hybrid-search', 'ハイブリッド検索', 'Hybrid Search', 'は', 'キーワード検索とベクトル検索を組み合わせる。', 2, 'g-kentei'),
    ('hallucination', 'ハルシネーション', 'Hallucination', '', 'AIが事実と異なる内容を自信を持って出力してしまう現象。生成AIの主要な課題のひとつ。', 2, 'g-kentei'),
    ('hallucination-mitigation', 'ハルシネーション対策', 'Hallucination Mitigation', 'は', '事実誤り出力を減らす技法の総称。', 1, 'g-kentei|genai-passport'),
    ('bias-mitigation-prompt', 'バイアス緩和プロンプト', 'Bias Mitigation Prompt', 'ば', '公平な出力を促す指示設計。', 2, 'g-kentei|genai-passport'),
    ('batch-inference', 'バッチ推論', 'Batch Inference', 'ば', '大量リクエストをまとめて非同期に推論する方式。', 2, 'g-kentei'),
    ('prompt', 'プロンプト', 'Prompt', '', 'AIに与える指示文・質問文のこと。プロンプトの書き方次第で出力の質が大きく変わる。', 2, 'g-kentei'),
    ('prompt-injection', 'プロンプトインジェクション', 'Prompt Injection', 'ぷ', '悪意ある指示でAIの制約を迂回させる攻撃。', 1, 'g-kentei|genai-passport'),
    ('prompt-engineering', 'プロンプトエンジニアリング', 'Prompt Engineering', '', 'AIから望む回答を引き出すための指示文を設計・最適化する技術。ビジネス活用において重要なスキル。', 2, 'g-kentei'),
    ('prompt-caching', 'プロンプトキャッシュ', 'Prompt Caching', 'ぷ', '同一プレフィックスを再利用しコスト・遅延を削減。', 2, 'g-kentei|genai-passport'),
    ('prompt-chaining', 'プロンプトチェーン', 'Prompt Chaining', 'ぷ', '複数プロンプトを順に繋ぎ複雑タスクを分解する。', 2, 'g-kentei|genai-passport'),
    ('prompt-template', 'プロンプトテンプレート', 'Prompt Template', 'ぷ', '再利用可能な指示文の型。変数を埋め込んで使う。', 2, 'g-kentei|genai-passport'),
    ('prompt-library', 'プロンプトライブラリ', 'Prompt Library', 'ぷ', '検証済みプロンプトを共有・再利用する集積。', 2, 'g-kentei|genai-passport'),
    ('vector-search', 'ベクトル検索', 'Vector Search', 'べ', '埋め込みの近傍探索で関連文書を取得する。', 2, 'g-kentei|genai-passport'),
    ('vendor-lock-in-ai', 'ベンダーロックイン', 'Vendor Lock-in', 'べ', '特定AIサービスに依存し乗り換えが難しい状態。', 2, 'g-kentei|genai-passport'),
    ('multi-agent', 'マルチエージェント', 'Multi-Agent', 'ま', '複数AIが協調・分担して問題を解く構成。', 2, 'g-kentei|genai-passport'),
    ('multi-turn-dialogue', 'マルチターン対話', 'Multi-turn Dialogue', 'ま', '複数往復の会話文脈を維持する対話形式。', 2, 'g-kentei|genai-passport'),
    ('multimodal-prompt', 'マルチモーダルプロンプト', 'Multimodal Prompt', 'ま', 'テキストと画像等を組み合わせた指示入力。', 2, 'g-kentei|genai-passport'),
    ('meta-prompt', 'メタプロンプト', 'Meta Prompt', 'め', 'プロンプト自体を生成・改善させる上位指示。', 2, 'g-kentei'),
    ('model-card-genai', 'モデル仕様', 'Model Specification', 'も', 'モデルの能力・制限・学習データ概要の公開情報。', 2, 'g-kentei|genai-passport'),
    ('model-serving', 'モデル配信', 'Model Serving', 'も', '学習済みモデルをAPI等で本番提供する仕組み。', 2, 'g-kentei'),
    ('moderation-api', 'モデレーションAPI', 'Moderation API', 'も', 'テキストや画像の安全性を判定するAPI。', 2, 'g-kentei|genai-passport'),
    ('user-prompt', 'ユーザープロンプト', 'User Prompt', 'ゆ', '利用者が入力する質問・指示文。', 2, 'g-kentei|genai-passport'),
    ('real-time-inference', 'リアルタイム推論', 'Real-time Inference', 'り', '低遅延で逐次応答する推論方式。', 2, 'g-kentei'),
    ('reranking', 'リランキング', 'Reranking', 'り', '初回検索結果をより精密なモデルで並べ替える。', 2, 'g-kentei'),
    ('responsible-ai', 'レスポンシブルAI', 'Responsible AI', 'れ', '公平・透明・安全なAI開発・利用の原則。', 2, 'g-kentei|genai-passport'),
    ('red-teaming', 'レッドチーミング', 'Red Teaming', 'れ', '意図的に弱点を探し安全性を検証する活動。', 2, 'g-kentei|genai-passport'),
    ('rate-limit', 'レート制限', 'Rate Limit', 'れ', 'API呼び出し回数やトークン量の上限。', 2, 'g-kentei|genai-passport'),
    ('long-context', 'ロングコンテキスト', 'Long Context', 'ろ', '非常に長い入力を扱えるモデル・技術の総称。', 2, 'g-kentei'),
    ('role-prompting', 'ロールプロンプト', 'Role Prompting', 'ろ', 'AIに役割・人格を与えて回答を誘導する技法。', 2, 'g-kentei|genai-passport'),
    ('human-preference', '人間の選好', 'Human Preference', 'に', '人がより良い回答を選ぶ信号。RLHFやDPOの基盤。', 2, 'g-kentei|genai-passport'),
    ('stop-sequence', '停止シーケンス', 'Stop Sequence', 'て', 'この文字列が出たら生成を止める設定。', 2, 'g-kentei|genai-passport'),
    ('input-token', '入力トークン', 'Input Token', 'に', 'プロンプトに含まれるトークン。課金対象になりやすい。', 2, 'g-kentei|genai-passport'),
    ('output-token', '出力トークン', 'Output Token', 'し', 'モデルが生成したトークン。', 2, 'g-kentei|genai-passport'),
    ('output-parser', '出力パーサ', 'Output Parser', 'し', 'LLM出力を構造化データへ変換するコンポーネント。', 2, 'g-kentei'),
    ('output-validation', '出力検証', 'Output Validation', 'し', '生成結果をスキーマやルールで検証する工程。', 2, 'g-kentei|genai-passport'),
    ('synthetic-data-generation', '合成データ生成', 'Synthetic Data Generation', 'ご', 'AIで学習・評価用データを人工的に作ること。', 2, 'g-kentei|genai-passport'),
    ('synthetic-prompt-data', '合成プロンプトデータ', 'Synthetic Prompt Data', 'ご', 'AIで作った指示データ。微調整や評価に使う。', 2, 'g-kentei'),
    ('synthetic-media', '合成メディア', 'Synthetic Media', 'ご', 'AI等で生成された画像・音声・動画コンテンツ。', 2, 'g-kentei|genai-passport'),
    ('few-shot-prompting', '少数ショットプロンプト', 'Few-shot Prompting', 'し', '少数の例をプロンプトに含めて性能を高める手法。', 2, 'g-kentei|genai-passport'),
    ('citation-generation', '引用付き生成', 'Citation Generation', 'い', '回答に出典を付けて根拠を示す生成方式。', 2, 'g-kentei|genai-passport'),
    ('refusal', '拒否応答', 'Refusal', 'き', 'モデルが不適切な要求を断る応答パターン。', 2, 'g-kentei|genai-passport'),
    ('instruction-dataset', '指示データセット', 'Instruction Dataset', 'し', '指示と応答のペアで構成された微調整用データ。', 2, 'g-kentei|genai-passport'),
    ('inference-endpoint', '推論エンドポイント', 'Inference Endpoint', 'す', 'モデル推論APIの公開URL・サービス接点。', 2, 'g-kentei'),
    ('inference-latency', '推論レイテンシ', 'Inference Latency', 'す', '推論リクエストから応答までの遅延時間。ユーザー体験とコストに直結する。', 2, 'g-kentei|genai-passport'),
    ('context-learning', '文脈内学習', 'In-Context Learning', 'ぶ', 'プロンプト内の例からタスクを即座に実行する能力。', 2, 'g-kentei|genai-passport'),
    ('max-tokens', '最大トークン数', 'Max Tokens', 'さ', '生成するトークン数の上限設定。', 2, 'g-kentei|genai-passport'),
    ('retrieval-precision', '検索精度', 'Retrieval Precision', 'け', 'RAGで取得文書がどれだけ関連していたか。', 2, 'g-kentei'),
    ('structured-output', '構造化出力', 'Structured Output', 'こ', 'スキーマに沿った形式で回答を得る仕組み。', 2, 'g-kentei|genai-passport'),
    ('temperature', '温度パラメータ', 'Temperature', 'お', '出力のランダム性を制御する生成パラメータ。', 2, 'g-kentei|genai-passport'),
    ('special-token', '特殊トークン', 'Special Token', 'と', '開始・終了・役割などに使う制御用トークン。', 2, 'g-kentei|genai-passport'),
    ('generative-ai-policy', '生成AI利用ポリシー', 'Generative AI Policy', 'せ', '組織内での生成AI利用ルールを定めた方針。', 2, 'g-kentei|genai-passport'),
    ('image-to-text', '画像キャプション生成', 'Image-to-Text', 'が', '画像の内容を文章で説明する生成タスク。', 2, 'g-kentei'),
    ('eos-token', '終了トークン', 'EOS Token', 'し', '生成終了を示す特殊トークン。', 2, 'g-kentei|genai-passport'),
    ('self-consistency', '自己整合性', 'Self-Consistency', 'じ', '複数推論経路の多数決で回答精度を上げる手法。', 2, 'g-kentei|genai-passport'),
    ('summarization-chain', '要約チェーン', 'Summarization Chain', 'よう', '長文を段階的に要約してコンテキストを圧縮する。', 2, 'g-kentei'),
    ('plan-and-execute', '計画と実行', 'Plan and Execute', 'け', '計画立案と実行を分離するエージェント設計。', 2, 'g-kentei'),
    ('eval-dataset', '評価データセット', 'Evaluation Dataset', 'ひ', 'モデル性能を測るためのベンチマークデータ。', 2, 'g-kentei'),
    ('super-resolution', '超解像', 'Super Resolution', 'ち', '低解像度画像から高解像度を推定生成する。', 2, 'g-kentei'),
    ('preference-dataset', '選好データセット', 'Preference Dataset', 'せ', '選好ペアで構成されたDPO等の学習データ。', 2, 'g-kentei'),
    ('preference-pair', '選好ペア', 'Preference Pair', 'せ', '良い回答と悪い回答のペア。選好学習に使う。', 2, 'g-kentei'),
    ('bos-token', '開始トークン', 'BOS Token', 'か', '系列開始を示す特殊トークン。', 2, 'g-kentei|genai-passport'),
    ('function-calling', '関数呼び出し', 'Function Calling', 'か', 'モデルが構造化された関数呼び出しを出力する機能。', 2, 'g-kentei|genai-passport'),
]
