"""案B: 倫理・ビジネス（184語）。"""

# id, name, yomi, reading, summary, tier, exams
TERMS = [
    ('ai-center-of-excellence', 'AI CoE', 'AI Center of Excellence', 'A', '組織内のAI推進・標準化を担う専門チーム。', 2, 'g-kentei'),
    ('sustainability-ai', 'AIと持続可能性', 'AI Sustainability', 'A', 'AIの環境負荷（エネルギー・水）と持続可能性。', 2, 'g-kentei|genai-passport'),
    ('ai-and-employment', 'AIと雇用', 'AI and Employment', 'A', 'AIが労働市場に与える影響と対策。', 2, 'g-kentei|genai-passport'),
    ('carbon-footprint-ai', 'AIのカーボンフットプリント', 'AI Carbon Footprint', 'A', '大規模学習・推論が生む温室効果ガス排出。', 2, 'g-kentei|genai-passport'),
    ('water-usage-ai', 'AIの水使用量', 'Water Usage in AI', 'A', 'データセンター冷却等による水資源への影響。', 2, 'g-kentei'),
    ('environmental-impact-ai', 'AIの環境影響', 'Environmental Impact of AI', 'A', '学習・推論のエネルギー・資源消費への配慮。', 2, 'g-kentei|genai-passport'),
    ('liability-ai', 'AIの責任', 'AI Liability', 'A', 'AIの誤動作・損害に対する法的責任の在り方。', 2, 'g-kentei|genai-passport'),
    ('ai-incident', 'AIインシデント', 'AI Incident', 'A', 'AIの誤動作・有害出力などの障害事象。', 2, 'g-kentei|genai-passport'),
    ('ai-engineer', 'AIエンジニア', 'AI Engineer', 'A', 'AIシステムの設計・実装・運用を行う技術者。', 2, 'g-kentei|genai-passport'),
    ('ai-governance', 'AIガバナンス', 'AI Governance', 'A', 'AIの開発・運用を組織的に統制・監督する枠組み。', 1, 'g-kentei|genai-passport'),
    ('ai-governance-board', 'AIガバナンス委員会', 'AI Governance Board', 'A', '経営層を含むAI統治の意思決定機関。', 2, 'g-kentei|genai-passport'),
    ('ai-consulting', 'AIコンサルティング', 'AI Consulting', 'A', '導入戦略・技術選定・実装を支援するコンサル。', 2, 'g-kentei|genai-passport'),
    ('ai-security', 'AIセキュリティ', 'AI Security', 'A', 'AIシステムへの攻撃・悪用から守る対策。', 2, 'g-kentei|genai-passport'),
    ('ai-champion', 'AIチャンピオン', 'AI Champion', 'A', '部門内でAI活用を推進する担い手。', 2, 'g-kentei|genai-passport'),
    ('ai-team', 'AIチーム編成', 'AI Team', 'A', 'データサイエンティスト・エンジニア等の役割分担。', 2, 'g-kentei|genai-passport'),
    ('ai-project-management', 'AIプロジェクト管理', 'AI Project Management', 'A', 'データ・モデル・運用を含むAI開発の計画と統制。', 2, 'g-kentei'),
    ('ai-product-manager', 'AIプロダクトマネージャー', 'AI Product Manager', 'A', 'AI機能の企画・要件定義・ロードマップを担う。', 2, 'g-kentei'),
    ('ai-risk-assessment', 'AIリスク評価', 'AI Risk Assessment', 'A', 'AI導入前後のリスクを特定・評価するプロセス。', 2, 'g-kentei|genai-passport'),
    ('ai-literacy-policy', 'AIリテラシー教育', 'AI Literacy Education', 'A', '組織・社会全体でのAI理解促進。', 2, 'g-kentei|genai-passport'),
    ('ai-literacy-training', 'AIリテラシー研修', 'AI Literacy Training', 'A', '全社員向けのAI基礎・安全利用教育。', 2, 'g-kentei|genai-passport'),
    ('ai-roadmap', 'AIロードマップ', 'AI Roadmap', 'A', 'AI機能・組織能力を時系列で計画した道筋。', 2, 'g-kentei|genai-passport'),
    ('ai-ethics-overview', 'AI倫理', 'AI Ethics', 'A', 'AIの開発・利用における公平性・安全性・責任の枠組み。', 1, 'g-kentei|genai-passport'),
    ('ai-ethics-principles', 'AI倫理原則', 'AI Ethics Principles', 'A', '人間中心・公平・プライバシー等の基本原則の集合。', 2, 'g-kentei|genai-passport'),
    ('ai-committee', 'AI委員会', 'AI Committee', 'A', '社内のAI導入・倫理を審議する組織。', 2, 'g-kentei|genai-passport'),
    ('ai-adoption', 'AI導入', 'AI Adoption', 'A', '組織がAI技術を業務に取り入れるプロセス。', 2, 'g-kentei|genai-passport'),
    ('ai-maturity-model', 'AI成熟度モデル', 'AI Maturity Model', 'A', '組織のAI活用レベルを段階的に評価する枠組み。', 2, 'g-kentei|genai-passport'),
    ('ai-strategy', 'AI戦略', 'AI Strategy', 'A', '組織がAIで競争優位を得るための中長期計画。', 2, 'g-kentei|genai-passport'),
    ('ai-generated-copyright', 'AI生成物の著作権', 'AI-generated Work Copyright', 'A', 'AIが生成したコンテンツの権利帰属に関する問題。', 1, 'g-kentei|genai-passport'),
    ('ai-audit', 'AI監査', 'AI Audit', 'A', 'AIシステムの公平性・安全性・法令遵守を検証する。', 2, 'g-kentei|genai-passport'),
    ('total-cost-of-ai', 'AI総コスト', 'Total Cost of AI', 'A', 'ライセンス・GPU・人件費を含むAI導入の総コスト。', 2, 'g-kentei|genai-passport'),
    ('ai-labeling', 'AI表示', 'AI Labeling', 'A', 'AI生成コンテンツであることを明示する義務・慣行。', 2, 'g-kentei|genai-passport'),
    ('ai-regulation-japan', 'AI規制（日本）', 'AI Regulation in Japan', 'A', '日本におけるAI関連の法整備・ガイドライン動向。', 2, 'g-kentei|genai-passport'),
    ('digital-transformation', 'DX', 'Digital Transformation', 'D', 'デジタル技術でビジネスモデル・業務を変革すること。', 2, 'g-kentei|genai-passport'),
    ('eu-ai-act', 'EU AI Act', 'EU AI Act', 'E', 'EUのAI規制法。リスクベースで義務を段階化。', 1, 'g-kentei|genai-passport'),
    ('gdpr', 'GDPR', 'General Data Protection Regulation', 'G', 'EUの一般データ保護規則。個人データ処理を厳格化。', 2, 'g-kentei|genai-passport'),
    ('iso-42001', 'ISO/IEC 42001', 'ISO/IEC 42001', 'I', 'AIマネジメントシステムの国際規格。', 2, 'g-kentei|genai-passport'),
    ('kpi', 'KPI', 'Key Performance Indicator', 'K', '目標達成度を測る重要業績評価指標。', 2, 'g-kentei|genai-passport'),
    ('ml-engineer', 'MLエンジニア', 'ML Engineer', 'M', 'モデルの本番運用・スケールを担うエンジニア。', 2, 'g-kentei|genai-passport'),
    ('mvp', 'MVP', 'Minimum Viable Product', 'M', '最小限の機能で価値検証するプロダクト。', 2, 'g-kentei'),
    ('build-vs-buy', 'Make or Buy', 'Build vs Buy', 'M', '自社開発か既製品購入かの判断。', 2, 'g-kentei|genai-passport'),
    ('nist-ai-rmf', 'NIST AI RMF', 'NIST AI Risk Management Framework', 'N', '米国NISTのAIリスク管理フレームワーク。', 2, 'g-kentei|genai-passport'),
    ('ai-principles-oecd', 'OECD AI原則', 'OECD AI Principles', 'O', 'OECDが掲げる信頼できるAIの国際原則。', 2, 'g-kentei'),
    ('okr', 'OKR', 'Objectives and Key Results', 'O', '目標と主要成果で進捗を管理するフレームワーク。', 2, 'g-kentei'),
    ('poc', 'PoC', 'Proof of Concept', 'P', '概念実証。本格導入前に技術・価値を小規模検証する。', 2, 'g-kentei|genai-passport'),
    ('pilot-success-criteria', 'PoC成功基準', 'PoC Success Criteria', 'P', '概念実証の合否を判断する定量・定性指標。', 2, 'g-kentei|genai-passport'),
    ('roi', 'ROI', 'Return on Investment', 'R', '投資対効果。AI導入の費用対便益を測る指標。', 2, 'g-kentei|genai-passport'),
    ('rpa', 'RPA', 'Robotic Process Automation', 'R', 'GUI操作をソフトウェアロボットで自動化する技術。', 2, 'g-kentei|genai-passport'),
    ('saas-ai', 'SaaS型AI', 'AI SaaS', 'S', 'クラウドでサブスクリプション提供されるAIサービス。', 2, 'g-kentei|genai-passport'),
    ('tco', 'TCO', 'Total Cost of Ownership', 'T', '導入から運用まで含む総所有コスト。', 2, 'g-kentei'),
    ('unesco-ai-ethics', 'UNESCO AI倫理', 'UNESCO Recommendation on AI Ethics', 'U', 'UNESCOのAI倫理に関する勧告。', 2, 'g-kentei'),
    ('accessibility-ai', 'アクセシビリティ', 'Accessibility', 'あ', '障害のある人もAIサービスを利用できること。', 2, 'g-kentei'),
    ('agile-development', 'アジャイル開発', 'Agile Development', 'あ', '短い反復で要件を柔軟に進める開発手法。', 2, 'g-kentei'),
    ('upskilling', 'アップスキリング', 'Upskilling', 'あ', '既存社員のAI関連スキルを高めること。', 2, 'g-kentei|genai-passport'),
    ('algorithmic-bias', 'アルゴリズムバイアス', 'Algorithmic Bias', 'あ', 'アルゴリズムが特定集団に不利な結果を生む偏り。', 1, 'g-kentei|genai-passport'),
    ('algorithmic-accountability', 'アルゴリズム説明責任', 'Algorithmic Accountability', 'あ', 'アルゴリズムの結果に対する説明・責任の所在。', 2, 'g-kentei|genai-passport'),
    ('algorithmic-transparency', 'アルゴリズム透明性', 'Algorithmic Transparency', 'あ', 'アルゴリズムの目的・データ・限界を開示すること。', 2, 'g-kentei'),
    ('inclusive-design', 'インクルーシブデザイン', 'Inclusive Design', 'い', '多様な利用者を排除しない設計アプローチ。', 2, 'g-kentei'),
    ('incident-response', 'インシデント対応', 'Incident Response', 'い', 'AI障害・誤動作発生時の初動と復旧手順。', 2, 'g-kentei|genai-passport'),
    ('industry-40', 'インダストリー4.0', 'Industry 4.0', 'い', '製造業のデジタル化・スマートファクトリー化。', 2, 'g-kentei'),
    ('intelligent-automation', 'インテリジェントオートメーション', 'Intelligent Automation', 'い', 'RPAとAIを組み合わせた高度自動化。', 2, 'g-kentei'),
    ('informed-consent', 'インフォームドコンセント', 'Informed Consent', 'い', '内容を理解した上での自由な同意。', 2, 'g-kentei'),
    ('opt-out-copyright', 'オプトアウト', 'Opt-out', 'お', '著作物のAI学習利用を拒否する仕組み・権利。', 2, 'g-kentei'),
    ('open-source-license', 'オープンソースライセンス', 'Open Source License', 'お', 'OSSモデル・コード利用時の義務・制限。', 2, 'g-kentei|genai-passport'),
    ('custom-ai-development', 'カスタムAI開発', 'Custom AI Development', 'か', '自社要件に合わせた独自AIシステムの開発。', 2, 'g-kentei'),
    ('kill-switch', 'キルスイッチ', 'Kill Switch', 'き', '危険時にAIシステムを停止する緊急機構。', 2, 'g-kentei'),
    ('cross-functional-team', 'クロスファンクショナルチーム', 'Cross-functional Team', 'く', '業務・IT・法務など横断でAI案件を進める体制。', 2, 'g-kentei'),
    ('green-ai', 'グリーンAI', 'Green AI', 'ぐ', '環境負荷を抑えた効率的なAI研究・運用。', 2, 'g-kentei'),
    ('cost-reduction', 'コスト削減', 'Cost Reduction', 'こ', 'AIによる業務効率化・自動化での費用圧縮。', 2, 'g-kentei|genai-passport'),
    ('supply-chain-risk', 'サプライチェーンリスク', 'Supply Chain Risk', 'さ', '外部モデル・データ依存に伴うセキュリティリスク。', 2, 'g-kentei|genai-passport'),
    ('service-catalog', 'サービスカタログ', 'Service Catalog', 'せ', '社内で利用可能なAIサービス一覧と利用条件。', 2, 'g-kentei'),
    ('citizen-developer', 'シチズンデベロッパー', 'Citizen Developer', 'し', '非専門家がローコード等でアプリを作る利用者。', 2, 'g-kentei|genai-passport'),
    ('scrum', 'スクラム', 'Scrum', 'す', 'アジャイルの代表的フレームワーク。', 2, 'g-kentei'),
    ('stakeholder', 'ステークホルダー', 'Stakeholder', 'す', 'AIプロジェクトに利害関係を持つ関係者。', 2, 'g-kentei|genai-passport'),
    ('stakeholder-mapping', 'ステークホルダーマップ', 'Stakeholder Mapping', 'す', '利害関係者と影響度を整理する手法。', 2, 'g-kentei'),
    ('smart-factory', 'スマートファクトリー', 'Smart Factory', 'す', 'IoTとAIで最適化された自律的な工場。', 2, 'g-kentei'),
    ('security-by-design', 'セキュリティバイデザイン', 'Security by Design', 'せ', '設計段階からセキュリティを組み込む考え方。', 2, 'g-kentei|genai-passport'),
    ('change-management', 'チェンジマネジメント', 'Change Management', 'ち', 'AI導入に伴う組織・文化の変化を管理すること。', 2, 'g-kentei|genai-passport'),
    ('chatbot-support', 'チャットボットサポート', 'Chatbot Support', 'ち', 'AIチャットで顧客問い合わせに自動応答する。', 2, 'g-kentei|genai-passport'),
    ('digital-divide', 'デジタルデバイド', 'Digital Divide', 'で', '技術へのアクセス格差。AIで拡大する懸念。', 2, 'g-kentei|genai-passport'),
    ('dual-use', 'デュアルユース', 'Dual Use', 'で', '民生・軍事両方に転用可能なAI技術の問題。', 2, 'g-kentei'),
    ('data-scientist', 'データサイエンティスト', 'Data Scientist', 'で', 'データ分析とモデル構築でビジネス課題を解く専門職。', 2, 'g-kentei|genai-passport'),
    ('data-steward', 'データスチュワード', 'Data Steward', 'で', 'データ品質と利用ルールを管理する担当者。', 2, 'g-kentei'),
    ('data-poisoning', 'データポイズニング', 'Data Poisoning', 'で', '訓練データに悪意あるサンプルを混入する攻撃。', 2, 'g-kentei'),
    ('data-residency', 'データレジデンシー', 'Data Residency', 'で', 'データが保存・処理される国・地域の要件。', 2, 'g-kentei|genai-passport'),
    ('data-subject-rights', 'データ主体の権利', 'Data Subject Rights', 'で', '本人が自己データについて行使できる権利群。', 2, 'g-kentei|genai-passport'),
    ('data-minimization', 'データ最小化', 'Data Minimization', 'で', '必要最小限のデータだけを収集・保持する原則。', 2, 'g-kentei|genai-passport'),
    ('knowledge-management', 'ナレッジマネジメント', 'Knowledge Management', 'な', '組織知を蓄積・共有・活用する仕組み。RAGと親和。', 2, 'g-kentei|genai-passport'),
    ('bias', 'バイアス', 'Bias', '', 'AIが偏ったデータで学習した結果、特定の集団や属性に対して不公平な予測をしてしまう問題。', 2, 'g-kentei'),
    ('backdoor-attack', 'バックドア攻撃', 'Backdoor Attack', 'ば', '特定トリガーで誤動作するよう仕込む攻撃。', 2, 'g-kentei'),
    ('pilot-project', 'パイロットプロジェクト', 'Pilot Project', 'ぱ', '限定範囲で本番に近い形でAIを試験導入する。', 2, 'g-kentei|genai-passport'),
    ('right-of-publicity', 'パブリシティ権', 'Right of Publicity', 'ぱ', '氏名・肖像の商業利用を支配する権利。', 2, 'g-kentei'),
    ('personalization', 'パーソナライゼーション', 'Personalization', 'ぱ', '個人に最適化したコンテンツ・提案を行うこと。', 2, 'g-kentei|genai-passport'),
    ('business-case', 'ビジネスケース', 'Business Case', 'び', '投資対効果を示しプロジェクト承認を得る資料。', 2, 'g-kentei|genai-passport'),
    ('business-value', 'ビジネス価値', 'Business Value', 'び', 'AIがもたらす収益・コスト削減・顧客満足などの価値。', 2, 'g-kentei|genai-passport'),
    ('privacy', 'プライバシー', 'Privacy', 'ぷ', '個人の情報や生活が不当に侵害されない権利・状態。', 2, 'g-kentei|genai-passport'),
    ('privacy-impact-assessment', 'プライバシー影響評価', 'Privacy Impact Assessment', 'ぷ', '個人データ処理のリスクを事前評価する手続き。', 2, 'g-kentei'),
    ('prompt-engineer-role', 'プロンプトエンジニア', 'Prompt Engineer', 'ぷ', 'LLM向け指示設計・評価を専門とする職種。', 2, 'g-kentei|genai-passport'),
    ('vendor-due-diligence', 'ベンダーデューデリジェンス', 'Vendor Due Diligence', 'べ', 'AIベンダーの信頼性・コンプライアンスを調査すること。', 2, 'g-kentei|genai-passport'),
    ('vendor-management', 'ベンダー管理', 'Vendor Management', 'べ', '外部AIベンダーとの契約・SLA・評価管理。', 2, 'g-kentei|genai-passport'),
    ('vendor-selection', 'ベンダー選定', 'Vendor Selection', 'べ', 'AI製品・サービス提供者を比較選定するプロセス。', 2, 'g-kentei|genai-passport'),
    ('my-number', 'マイナンバー', 'My Number', 'ま', '日本の個人番号制度。AI利用時の取扱いに注意が必要。', 2, 'g-kentei'),
    ('model-owner', 'モデルオーナー', 'Model Owner', 'も', '本番モデルの責任者。性能・リスクに説明責任。', 2, 'g-kentei'),
    ('model-governance-ethics', 'モデルガバナンス', 'Model Governance', 'も', 'モデルの開発・運用を統制する枠組み。', 2, 'g-kentei|genai-passport'),
    ('model-poisoning', 'モデルポイズニング', 'Model Poisoning', 'も', '学習データを改ざんしモデルを劣化・悪用させる攻撃。', 2, 'g-kentei'),
    ('model-stealing', 'モデル窃取', 'Model Stealing', 'も', 'API問い合わせでモデルを複製しようとする攻撃。', 2, 'g-kentei'),
    ('user-story', 'ユーザーストーリー', 'User Story', 'ゆ', '利用者視点の要求を短い文章で表現する。', 2, 'g-kentei'),
    ('use-case', 'ユースケース', 'Use Case', 'ゆ', 'AIを適用する具体的な業務シーン・利用場面。', 2, 'g-kentei|genai-passport'),
    ('use-case-prioritization', 'ユースケース優先順位', 'Use Case Prioritization', 'ゆ', 'ROIと実現性でAI案件の優先度を決める。', 2, 'g-kentei|genai-passport'),
    ('reskilling', 'リスキリング', 'Reskilling', 'り', '新しい職種・スキルへ転換する再教育。', 2, 'g-kentei|genai-passport'),
    ('risk-based-regulation', 'リスクベース規制', 'Risk-based Regulation', 'り', 'AIの用途リスクに応じて規制強度を変える考え方。', 2, 'g-kentei|genai-passport'),
    ('workflow-automation', 'ワークフロー自動化', 'Workflow Automation', 'わ', '承認・通知など業務フローを自動化する。', 2, 'g-kentei|genai-passport'),
    ('fraud-detection', '不正検知', 'Fraud Detection', 'ふ', '取引パターンから不正をAIで検出する。', 2, 'g-kentei'),
    ('predictive-maintenance', '予知保全', 'Predictive Maintenance', 'よ', 'センサーデータから故障を予測し保全する。', 2, 'g-kentei'),
    ('human-oversight-ethics', '人間による監督', 'Human Oversight', 'に', '高リスクAIに求められる人の監視・介入。', 2, 'g-kentei|genai-passport'),
    ('human-dignity', '人間の尊厳', 'Human Dignity', 'に', 'AIが人の尊厳を損なわないことを求める倫理原則。', 2, 'g-kentei|genai-passport'),
    ('human-oversight', '人間の監督', 'Human Oversight', 'に', 'AIの運用に人が最終判断・監視を行う要件。', 2, 'g-kentei|genai-passport'),
    ('human-centric-ai', '人間中心のAI', 'Human-centric AI', 'に', '人間の尊厳と福祉を最優先するAI設計思想。', 2, 'g-kentei|genai-passport'),
    ('pseudonymization', '仮名化', 'Pseudonymization', 'か', '識別子を置き換え再識別リスクを下げる加工。', 2, 'g-kentei'),
    ('corporate-ai-policy', '企業AIポリシー', 'Corporate AI Policy', 'き', '社内のAI利用・開発ルールを定めた方針文書。', 2, 'g-kentei|genai-passport'),
    ('value-alignment', '価値整合', 'Value Alignment', 'か', 'AIの目標を人間の価値観と一致させること。', 2, 'g-kentei'),
    ('personal-information', '個人情報', 'Personal Information', 'こ', '個人を識別できる情報。保護法制の対象。', 1, 'g-kentei|genai-passport'),
    ('appi', '個人情報保護法', 'Act on Protection of Personal Information', 'こ', '日本の個人情報保護に関する基本法律。', 1, 'g-kentei|genai-passport'),
    ('ethics-by-design', '倫理 by Design', 'Ethics by Design', 'り', '設計段階から倫理要件を組み込む考え方。', 2, 'g-kentei|genai-passport'),
    ('ethics-committee', '倫理委員会', 'Ethics Committee', 'り', 'AIプロジェクトの倫理的妥当性を審議する組織。', 2, 'g-kentei|genai-passport'),
    ('disinformation', '偽情報', 'Disinformation', 'ぎ', '意図的に作られた誤情報。生成AIで拡散リスクが増大。', 2, 'g-kentei|genai-passport'),
    ('child-data-protection', '児童データ保護', 'Child Data Protection', 'じ', '未成年のデータを特に慎重に扱う原則。', 2, 'g-kentei|genai-passport'),
    ('child-safety-ai', '児童保護', 'Child Safety in AI', 'じ', '未成年への有害コンテンツ・誘導を防ぐ配慮。', 2, 'g-kentei|genai-passport'),
    ('fairness', '公平性', 'Fairness', 'こ', 'AIが属性に関わらず公正な結果を出すこと。', 1, 'g-kentei|genai-passport'),
    ('whistleblowing-ai', '内部告発', 'Whistleblowing', 'な', 'AIの危険な利用を組織内外に通報する制度。', 2, 'g-kentei'),
    ('purpose-limitation', '利用目的の限定', 'Purpose Limitation', 'り', '収集時に示した目的の範囲でデータを使う原則。', 2, 'g-kentei'),
    ('acceptable-use-policy', '利用規定', 'Acceptable Use Policy', 'り', 'AIツールの許容・禁止行為を定めた社内規程。', 2, 'g-kentei|genai-passport'),
    ('terms-of-service-ai', '利用規約（AI）', 'Terms of Service', 'り', 'AIサービス提供者と利用者の契約条件。', 2, 'g-kentei|genai-passport'),
    ('benefit-realization', '効果実現', 'Benefit Realization', 'こ', '導入後に想定したビジネス効果が出ているか検証。', 2, 'g-kentei|genai-passport'),
    ('anonymization', '匿名化', 'Anonymization', 'と', '個人を特定できないようデータを加工すること。', 2, 'g-kentei|genai-passport'),
    ('acceptance-criteria', '受け入れ基準', 'Acceptance Criteria', 'う', '成果物が完了とみなされる条件。', 2, 'g-kentei'),
    ('consent', '同意', 'Consent', 'ど', '個人データやAI利用について本人の了解を得ること。', 2, 'g-kentei|genai-passport'),
    ('consent-management', '同意管理', 'Consent Management', 'ど', 'データ利用・AI処理について同意を記録・管理。', 2, 'g-kentei|genai-passport'),
    ('defamation', '名誉毀損', 'Defamation', 'め', 'AI生成の虚偽情報が他者の名誉を傷つけるリスク。', 2, 'g-kentei|genai-passport'),
    ('quality-inspection', '品質検査AI', 'AI Quality Inspection', 'ひ', '画像認識等で製品不良を自動検出する。', 2, 'g-kentei'),
    ('commercial-use-license', '商用利用ライセンス', 'Commercial Use License', 'し', 'AIモデル・データの商用利用可否を定める契約条件。', 2, 'g-kentei|genai-passport'),
    ('change-request', '変更要求', 'Change Request', 'へ', '本番AIシステムへの変更を管理するプロセス。', 2, 'g-kentei'),
    ('training-data-copyright', '学習データの著作権', 'Training Data Copyright', 'が', '著作物を学習に使うことの適法性に関する論点。', 2, 'g-kentei|genai-passport'),
    ('rollout-plan', '展開計画', 'Rollout Plan', 'て', 'パイロットから本番展開までの段階計画。', 2, 'g-kentei|genai-passport'),
    ('differential-privacy', '差分プライバシー', 'Differential Privacy', 'さ', '個々のデータ影響を数学的に制限するプライバシー枠組み。', 2, 'g-kentei'),
    ('discrimination', '差別', 'Discrimination', 'さ', '属性に基づく不当な扱い。AIが増幅する恐れ。', 2, 'g-kentei|genai-passport'),
    ('age-verification', '年齢確認', 'Age Verification', 'ね', '利用者の年齢を確認し保護措置を講じる仕組み。', 2, 'g-kentei'),
    ('impact-assessment', '影響評価', 'Impact Assessment', 'え', 'AIが人権・社会に与える影響を事前評価する。', 2, 'g-kentei|genai-passport'),
    ('right-to-be-forgotten', '忘れられる権利', 'Right to be Forgotten', 'わ', '個人データの削除を求める権利。', 2, 'g-kentei|genai-passport'),
    ('document-automation', '文書業務自動化', 'Document Automation', 'ぶ', '契約書・報告書の作成・要約をAIで効率化。', 2, 'g-kentei|genai-passport'),
    ('disparate-impact', '格差影響', 'Disparate Impact', 'か', '一見中立な基準が特定集団に不利に働くこと。', 2, 'g-kentei'),
    ('workflow-integration', '業務フロー統合', 'Workflow Integration', 'ぎ', 'AIを既存業務プロセスに組み込むこと。', 2, 'g-kentei|genai-passport'),
    ('automation', '業務自動化', 'Business Automation', 'ぎ', '定型業務をAIやRPAで無人化すること。', 2, 'g-kentei|genai-passport'),
    ('confidential-data-leak', '機密情報漏洩', 'Confidential Data Leak', 'き', '生成AIへの入力で社外秘が流出するリスク。', 1, 'g-kentei|genai-passport'),
    ('biometric-data', '生体情報', 'Biometric Data', 'せ', '顔・指紋・声紋など個人を識別する身体的特徴データ。', 2, 'g-kentei|genai-passport'),
    ('productivity', '生産性向上', 'Productivity Improvement', 'せ', '同じリソースでより多くの成果を出すこと。', 2, 'g-kentei|genai-passport'),
    ('surveillance', '監視', 'Surveillance', 'か', 'AIによる大規模監視とプライバシー・人権の緊張。', 2, 'g-kentei|genai-passport'),
    ('intellectual-property', '知的財産権', 'Intellectual Property Rights', '', 'AI生成コンテンツの著作権帰属をめぐる法律上の問題。各国で法整備が進行中。', 2, 'g-kentei'),
    ('prohibited-ai', '禁止AI', 'Prohibited AI', 'き', '社会通念上許容されないAI用途。例：社会点数悪用。', 2, 'g-kentei|genai-passport'),
    ('third-party-ai', '第三者AI', 'Third-party AI', 'だ', '外部ベンダーのAIを組み込む際のリスク管理。', 2, 'g-kentei|genai-passport'),
    ('third-party-risk', '第三者リスク', 'Third-party Risk', 'だ', '外部AI・データ提供者に依存するリスク。', 2, 'g-kentei|genai-passport'),
    ('continuous-improvement', '継続的改善', 'Continuous Improvement', 'け', '運用データに基づきモデル・プロセスを改善する。', 2, 'g-kentei'),
    ('portrait-right', '肖像権', 'Portrait Right', 'し', '自分の容貌が不当に公開・利用されない権利。', 2, 'g-kentei|genai-passport'),
    ('automated-decision-making', '自動化された意思決定', 'Automated Decision-making', 'じ', '人の介入なしにAIが個人に影響する決定を行うこと。', 2, 'g-kentei|genai-passport'),
    ('autonomous-weapons', '自律型兵器', 'Autonomous Weapons', 'じ', '人の操作なしに標的を選び攻撃する兵器。国際議論中。', 2, 'g-kentei'),
    ('copyright', '著作権', 'Copyright', 'ち', '創作物に対する排他的権利。AI生成物の扱いが議論中。', 1, 'g-kentei|genai-passport'),
    ('product-liability', '製造物責任', 'Product Liability', 'せ', '欠陥製品による損害で製造者が負う責任。', 2, 'g-kentei'),
    ('requirements-definition', '要件定義', 'Requirements Definition', 'よ', 'AIシステムに求める機能・性能を明確化する。', 2, 'g-kentei|genai-passport'),
    ('churn-prediction', '解約予測', 'Churn Prediction', 'か', '顧客離反の可能性を予測し施策につなげる。', 2, 'g-kentei'),
    ('misinformation', '誤情報', 'Misinformation', 'ご', '意図なく拡散された誤った情報。', 2, 'g-kentei|genai-passport'),
    ('right-to-explanation', '説明を受ける権利', 'Right to Explanation', 'せ', '自動化された決定について説明を求める権利。', 2, 'g-kentei|genai-passport'),
    ('accountability', '説明責任', 'Accountability', 'せ', 'AIの結果に対し誰が責任を負うかを明確にすること。', 2, 'g-kentei|genai-passport'),
    ('meeting-summary', '議事録自動生成', 'Meeting Summary', 'ぎ', '会議音声・文字起こしから要約を生成する。', 2, 'g-kentei|genai-passport'),
    ('cross-border-data', '越境データ移転', 'Cross-border Data Transfer', 'え', '国境を越えた個人データの送受信。規制対象。', 2, 'g-kentei'),
    ('transparency', '透明性', 'Transparency', 'と', 'AIの判断過程や限界を利用者が理解できること。', 2, 'g-kentei|genai-passport'),
    ('transparency-report', '透明性レポート', 'Transparency Report', 'と', 'AIシステムの能力・限界を公開する報告書。', 2, 'g-kentei|genai-passport'),
    ('operating-model', '運用モデル', 'Operating Model', 'う', 'AIサービスを誰がどう運用するかの体制設計。', 2, 'g-kentei'),
    ('operational-excellence', '運用卓越', 'Operational Excellence', 'う', '安定運用と継続改善を両立する運用体制。', 2, 'g-kentei'),
    ('negligence', '過失', 'Negligence', 'か', '注意義務違反による法的責任。AI運用でも問われうる。', 2, 'g-kentei'),
    ('conformity-assessment', '適合性評価', 'Conformity Assessment', 'て', 'AIシステムが規制要件を満たすか審査すること。', 2, 'g-kentei'),
    ('long-term-risk', '長期リスク', 'Long-term Risk', 'ち', '高度AIが将来にもたらす存続的リスクの議論。', 2, 'g-kentei'),
    ('labor-displacement', '雇用代替', 'Labor Displacement', 'こ', 'AIによる仕事の自動化・消失の可能性。', 2, 'g-kentei|genai-passport'),
    ('facial-recognition-ethics', '顔認識の倫理', 'Facial Recognition Ethics', 'か', '顔認識の誤認・差別・監視社会への懸念。', 2, 'g-kentei|genai-passport'),
    ('customer-segmentation', '顧客セグメンテーション', 'Customer Segmentation', 'こ', '顧客をグループ分けしマーケティングを最適化。', 2, 'g-kentei'),
    ('high-risk-ai', '高リスクAI', 'High-risk AI', 'こ', 'EU AI Act等で厳しい要件が課されるAI用途区分。', 2, 'g-kentei|genai-passport'),
]
