"""案B: モデル・技術（421語）。"""

# id, name, yomi, reading, summary, tier, exams
TERMS = [
    ('3d-cnn', '3D CNN', '3D Convolutional Network', '3', '時間軸も含め畳み込む動画向けネット。', 2, 'g-kentei'),
    ('albert', 'ALBERT', 'ALBERT', 'A', 'パラメータ共有で軽量化したBERT派生。', 3, 'g-kentei'),
    ('alibi', 'ALiBi', 'Attention with Linear Biases', 'A', '学習不要の位置バイアスで長文外挿を改善。', 2, 'g-kentei'),
    ('adam', 'Adam', 'Adam', 'A', '適応的学習率で広く使われる最適化アルゴリズム。', 2, 'g-kentei'),
    ('adamw', 'AdamW', 'AdamW', 'A', '重み減衰を正しく分離したAdamの改良版。', 2, 'g-kentei'),
    ('alexnet', 'AlexNet', 'AlexNet', 'A', 'ImageNetで深層学習ブームを起こした先駆的CNN。', 2, 'g-kentei'),
    ('bart-model', 'BART', 'BART', 'B', 'ノイズ破損から復元するエンコーダ・デコーダ事前学習。', 2, 'g-kentei'),
    ('bert', 'BERT', 'Bidirectional Encoder Representations from Transformers', '', 'Googleが開発した自然言語処理モデル。文の前後の文脈を同時に考慮する双方向学習が特徴。', 2, 'g-kentei'),
    ('beit', 'BEiT', 'BERT Pre-training of Image Transformers', 'B', 'マスク画像モデリングでViTを事前学習する手法。', 2, 'g-kentei'),
    ('bleu', 'BLEU', 'BLEU', 'B', '機械翻訳のn-gram一致に基づく評価指標。', 2, 'g-kentei'),
    ('bleu-score', 'BLEUスコア', 'BLEU Score', 'B', '翻訳品質のn-gram一致に基づく自動評価指標。', 2, 'g-kentei'),
    ('blip', 'BLIP', 'BLIP', 'B', '画像キャプション・VQA向けの視覚言語事前学習モデル。', 2, 'g-kentei'),
    ('bm25', 'BM25', 'BM25', 'B', 'キーワード検索で広く使われるランキング関数。', 2, 'g-kentei'),
    ('bpe', 'BPE', 'Byte Pair Encoding', 'B', '頻出ペアを統合して語彙を構築するトークン化。', 2, 'g-kentei'),
    ('bag-of-words', 'Bag of Words', 'Bag of Words', 'B', '語の出現回数ベクトルで文書を表現する手法。', 2, 'g-kentei'),
    ('cbam', 'CBAM', 'Convolutional Block Attention Module', 'C', 'チャネルと空間の注意を組み合わせたCNNモジュール。', 2, 'g-kentei'),
    ('clip-model', 'CLIP', 'CLIP', 'C', '画像とテキストを共通空間に埋め込む対照学習モデル。', 2, 'g-kentei'),
    ('cnn', 'CNN', '畳み込みニューラルネットワーク', '', '画像認識に特化したニューラルネットワークの一種。フィルターを使って画像の特徴を段階的に抽出する。', 2, 'g-kentei'),
    ('coco-dataset', 'COCO', 'COCO', 'C', '物体検出・セグメンテーションの標準データセット。', 2, 'g-kentei'),
    ('ctc', 'CTC', 'Connectionist Temporal Classification', 'C', '整列なしで系列ラベル学習を可能にする損失。', 2, 'g-kentei'),
    ('cuda', 'CUDA', 'CUDA', 'C', 'NVIDIA GPU向け並列計算プラットフォーム。', 2, 'g-kentei'),
    ('claude-model', 'Claude', 'Claude', 'C', 'Anthropicの対話型大規模言語モデルファミリー。安全性重視の設計。', 2, 'g-kentei|genai-passport'),
    ('codex-model', 'Codex', 'Codex', 'C', 'OpenAIのコード生成特化モデル。GitHub Copilotの基盤。', 2, 'g-kentei'),
    ('constitutional-ai', 'Constitutional AI', 'Constitutional AI', 'C', '原則に基づき自己修正する安全志向の学習手法。', 2, 'g-kentei'),
    ('controlnet', 'ControlNet', 'ControlNet', 'C', '追加条件で拡散モデルの生成を制御する仕組み。', 2, 'g-kentei'),
    ('cutmix', 'CutMix', 'CutMix', 'C', '画像の一部を別画像で置換するデータ拡張。', 2, 'g-kentei'),
    ('cyclegan', 'CycleGAN', 'CycleGAN', 'C', 'ペアなしデータでドメイン変換を行うGAN。', 2, 'g-kentei'),
    ('dalle-model', 'DALL·E', 'DALL·E', 'D', 'OpenAIのテキストから画像を生成する拡散モデル系列。', 2, 'g-kentei|genai-passport'),
    ('ddpm', 'DDPM', 'Denoising Diffusion Probabilistic Model', 'D', '確率的拡散モデルの代表的手法。', 2, 'g-kentei'),
    ('detr', 'DETR', 'Detection Transformer', 'D', 'Transformerで端から端の物体検出を行うモデル。', 2, 'g-kentei'),
    ('dpo', 'DPO', 'Direct Preference Optimization', 'D', '好みデータから直接方策を最適化する手法。', 2, 'g-kentei'),
    ('deberta', 'DeBERTa', 'DeBERTa', 'D', '分離注意と強化マスクで性能を高めたBERT系モデル。', 3, 'g-kentei'),
    ('deepseek', 'DeepSeek', 'DeepSeek', 'D', '中国発の高性能オープンウェイトLLMファミリー。', 2, 'g-kentei'),
    ('densenet', 'DenseNet', 'DenseNet', 'D', '層間を密結合し特徴を再利用するCNNアーキテクチャ。', 2, 'g-kentei'),
    ('dice-loss', 'Dice Loss', 'Dice Loss', 'D', 'セグメンテーションで重なりを直接最適化する損失。', 2, 'g-kentei'),
    ('electra', 'ELECTRA', 'ELECTRA', 'E', '判別的事前学習で効率的に学習するモデル。', 3, 'g-kentei'),
    ('elmo', 'ELMo', 'ELMo', 'E', '双方向LSTMの文脈埋め込み。Transformer前の代表的手法。', 2, 'g-kentei'),
    ('efficientnet', 'EfficientNet', 'EfficientNet', 'E', '深さ・幅・解像度を复合スケールした効率CNN。', 2, 'g-kentei'),
    ('embedding', 'Embedding', '埋め込み表現', '', '単語や文章を数値ベクトルに変換する技術。意味が近い言葉はベクトル空間上でも近い位置に配置される。', 2, 'g-kentei'),
    ('fcn', 'FCN', 'Fully Convolutional Network', 'F', 'ピクセル単位予測のため全結合を畳み込みに置換したネット。', 2, 'g-kentei'),
    ('flux-model', 'FLUX', 'FLUX', 'F', 'Black Forest Labsの高品質テキスト画像生成モデルファミリー。', 2, 'g-kentei'),
    ('fpn', 'FPN', 'Feature Pyramid Network', 'F', 'トップダウンと横接続でマルチスケール特徴を構築。', 2, 'g-kentei'),
    ('falcon-llm', 'Falcon', 'Falcon', 'F', 'TIIのオープンウェイト大規模言語モデルファミリー。', 2, 'g-kentei'),
    ('faster-rcnn', 'Faster R-CNN', 'Faster R-CNN', 'F', '領域提案ネットを統合した高速R-CNN。', 2, 'g-kentei'),
    ('flash-attention', 'FlashAttention', 'Flash Attention', 'F', 'メモリ効率の良い高速注意実装。', 2, 'g-kentei'),
    ('focal-loss', 'Focal Loss', 'Focal Loss', 'F', '難例に重みを置く分類損失。不均衡検出で有効。', 2, 'g-kentei'),
    ('foundation-model', 'Foundation Model', '基盤モデル', '', '大量のデータで事前学習された汎用的な大規模AIモデル。GPTやBERTなどが代表例で、様々なタスクに応用できる。', 2, 'g-kentei'),
    ('gan', 'GAN', '敵対的生成ネットワーク', '', '生成器と識別器が競い合いながら学習するモデル。リアルな画像・音声・動画の生成に使われる。', 2, 'g-kentei'),
    ('graph-attention-network', 'GAT', 'Graph Attention Network', 'G', 'グラフの近傍に注意機構を適用するGNN。', 2, 'g-kentei'),
    ('gcn', 'GCN', 'Graph Convolutional Network', 'G', 'グラフ上で近傍集約する畳み込み的演算。', 2, 'g-kentei'),
    ('gelu', 'GELU', 'Gaussian Error Linear Unit', 'G', 'Transformer系でよく使われる滑らかな活性化関数。', 2, 'g-kentei'),
    ('gpt', 'GPT', 'Generative Pre-trained Transformer', '', 'OpenAIが開発した大規模言語モデルシリーズ。ChatGPTの基盤であり、文章生成・翻訳・要約など幅広いタスクに対応する。', 2, 'g-kentei'),
    ('gpt-3', 'GPT-3', 'GPT-3', 'G', '1750億パラメータ規模で注目を集めた自己回帰言語モデル。', 2, 'g-kentei'),
    ('gpt-4', 'GPT-4', 'GPT-4', 'G', 'OpenAIのマルチモーダル対応大規模言語モデル。推論・コーディングで高性能。', 2, 'g-kentei|genai-passport'),
    ('gpt-4o', 'GPT-4o', 'GPT-4o', 'G', 'テキスト・画像・音声を統合処理するOpenAIのオムニモデル。', 2, 'g-kentei|genai-passport'),
    ('gpt-architecture', 'GPTアーキテクチャ', 'GPT Architecture', 'G', 'デコーダのみTransformerによる自己回帰言語モデル。', 2, 'g-kentei'),
    ('grouped-query-attention', 'GQA', 'Grouped Query Attention', 'G', 'KVヘッドをグループ化し注意計算を効率化。', 2, 'g-kentei'),
    ('gru', 'GRU', 'Gated Recurrent Unit', 'G', 'LSTMより単純なゲート付きRNN。', 2, 'g-kentei'),
    ('gemini-model', 'Gemini', 'Gemini', 'G', 'Googleのマルチモーダル大規模言語モデルファミリー。', 2, 'g-kentei|genai-passport'),
    ('gemma', 'Gemma', 'Gemma', 'G', 'Googleのオープンウェイト軽量LLMファミリー。', 2, 'g-kentei'),
    ('glove', 'GloVe', 'GloVe', 'G', '共起統計から単語ベクトルを学習する手法。', 2, 'g-kentei'),
    ('googlenet', 'GoogLeNet', 'GoogLeNet', 'G', 'インセプションモジュールで効率化したCNN。', 2, 'g-kentei'),
    ('hog', 'HOG', 'Histogram of Oriented Gradients', 'H', '勾配方向ヒストグラムで形状特徴を表現する古典的手法。', 2, 'g-kentei'),
    ('he-initialization', 'He初期化', 'He Initialization', 'H', 'ReLU向けの分散調整初期化。', 2, 'g-kentei'),
    ('huber-loss', 'Huber損失', 'Huber Loss', 'H', '外れ値に頑健な回帰損失。', 2, 'g-kentei'),
    ('human-eval', 'HumanEval', 'HumanEval', 'H', 'コード生成能力を測るベンチマーク。', 2, 'g-kentei'),
    ('image-dataset-imagenet', 'ImageNet', 'ImageNet', 'I', '大規模画像分類データセット。深層学習の転機となった。', 2, 'g-kentei'),
    ('imagen', 'Imagen', 'Imagen', 'I', 'Googleのテキスト画像生成拡散モデルファミリー。', 2, 'g-kentei'),
    ('inception', 'Inception', 'Inception', 'I', '多スケール畳み込みを並列化したCNNファミリー。', 2, 'g-kentei'),
    ('iou', 'IoU', 'Intersection over Union', 'I', '予測と正解ボックスの重なり度合い指標。', 2, 'g-kentei'),
    ('jax', 'JAX', 'JAX', 'J', '自動微分とJITを備えた数値計算ライブラリ。', 2, 'g-kentei'),
    ('kv-cache', 'KVキャッシュ', 'KV Cache', 'K', '推論時に鍵・値テンソルを再利用し生成を高速化。', 2, 'g-kentei'),
    ('keras', 'Keras', 'Keras', 'K', '高水準APIでモデルを組み立てるDLライブラリ。', 2, 'g-kentei'),
    ('lda', 'LDA', 'Latent Dirichlet Allocation', 'L', '文書・単語・トピックの確率モデル。', 2, 'g-kentei'),
    ('llm', 'LLM', '大規模言語モデル', '', '大量のテキストデータで学習した巨大な言語モデル。GPT・Claude・Geminiなどが代表例。', 2, 'g-kentei'),
    ('llama', 'LLaMA', 'LLaMA', 'L', 'Metaのオープン系大規模言語モデルファミリー。', 2, 'g-kentei'),
    ('llava', 'LLaVA', 'LLaVA', 'L', '大規模言語モデルと視覚エンコーダを結合したVLM。', 2, 'g-kentei'),
    ('lstm', 'LSTM', 'Long Short-Term Memory', 'L', 'ゲートで長期依存を学習するRNNの改良。', 2, 'g-kentei'),
    ('leaky-relu', 'Leaky ReLU', 'Leaky ReLU', 'L', '負領域にも小さな勾配を残すReLUの改良。', 2, 'g-kentei'),
    ('lidar', 'LiDAR', 'LiDAR', 'L', 'レーザーで距離を測り3D点群を取得するセンサー。', 2, 'g-kentei'),
    ('lora', 'LoRA', 'Low-Rank Adaptation', 'L', '低ランク行列で効率的にファインチューニングする技法。', 1, 'g-kentei|genai-passport'),
    ('lora-rank', 'LoRAランク', 'LoRA Rank', 'L', 'LoRAの低ランク行列の次元。表現力とコストのトレードオフ。', 2, 'g-kentei|genai-passport'),
    ('masked-autoencoder', 'MAE', 'Masked Autoencoder', 'M', '画像パッチをマスクして再構成する自己教師あり学習。', 2, 'g-kentei'),
    ('benchmark-mmlu', 'MMLU', 'MMLU', 'M', '多分野知識を測る大規模言語モデルベンチマーク。', 2, 'g-kentei'),
    ('multi-query-attention', 'MQA', 'Multi-Query Attention', 'M', '全ヘッドでKVを共有し推論を高速化。', 2, 'g-kentei'),
    ('mask-rcnn', 'Mask R-CNN', 'Mask R-CNN', 'M', '物体検出に加えインスタンスセグメンテーションを行う。', 2, 'g-kentei'),
    ('mecab', 'MeCab', 'MeCab', 'M', '日本語形態素解析の定番オープンソースツール。', 2, 'g-kentei'),
    ('mistral', 'Mistral', 'Mistral', 'M', '効率的なオープンウェイトLLMファミリー。', 2, 'g-kentei'),
    ('mixtral', 'Mixtral', 'Mixtral', 'M', 'Mistral AIの混合エキスパート（MoE）オープンLLM。', 2, 'g-kentei'),
    ('mixup', 'Mixup', 'Mixup', 'M', 'サンプルとラベルを線形補間して汎化を高める。', 2, 'g-kentei'),
    ('moco', 'MoCo', 'Momentum Contrast', 'M', '動量更新キューで対照学習を安定化する手法。', 3, 'g-kentei'),
    ('moe', 'MoE', 'Mixture of Experts', 'M', 'MoEの略。大規模モデルの効率化に使われる。', 2, 'g-kentei'),
    ('mobilenet', 'MobileNet', 'MobileNet', 'M', '深度別畳み込みで軽量・高速なモバイル向けCNN。', 2, 'g-kentei'),
    ('n-gram', 'N-gram', 'N-gram', 'N', '連続n語の系列特徴。言語モデルの基本単位。', 2, 'g-kentei'),
    ('neural-architecture-search', 'NAS', 'Neural Architecture Search', 'N', 'アーキテクチャ自体を自動探索する研究領域。', 2, 'g-kentei'),
    ('nlp', 'NLP', '自然言語処理', '', '人間が日常的に使う言語をコンピュータが理解・生成するための技術分野。翻訳・要約・感情分析などに活用される。', 2, 'g-kentei'),
    ('nltk', 'NLTK', 'NLTK', 'N', '教育・研究向けの古典的NLPツールキット。', 2, 'g-kentei'),
    ('nt-xent-loss', 'NT-Xent損失', 'NT-Xent Loss', 'N', '正規化温度付き対照損失。自己教師ありで使用。', 2, 'g-kentei'),
    ('nerf', 'NeRF', 'Neural Radiance Fields', 'N', 'ニューラル場で新規視点画像を合成する手法。', 2, 'g-kentei'),
    ('optical-character-recognition', 'OCR', 'Optical Character Recognition', 'O', '画像中の文字を認識してテキスト化する技術。', 2, 'g-kentei|genai-passport'),
    ('onnx', 'ONNX', 'Open Neural Network Exchange', 'O', 'モデル交換の共通フォーマット。', 2, 'g-kentei'),
    ('onnx-runtime', 'ONNX Runtime', 'ONNX Runtime', 'O', 'ONNXモデルの高速推論ランタイム。', 2, 'g-kentei'),
    ('orb', 'ORB', 'ORB', 'O', '高速なバイナリ特徴記述子。', 2, 'g-kentei'),
    ('o1-model', 'OpenAI o1', 'OpenAI o1', 'O', '推論特化の連鎖思考で難問に強いOpenAIモデル系列。', 2, 'g-kentei'),
    ('peft', 'PEFT', 'Parameter-Efficient Fine-Tuning', 'P', '一部パラメータだけを更新する効率的微調整の総称。', 2, 'g-kentei'),
    ('palm-model', 'PaLM', 'PaLM', 'P', 'Googleの大規模言語モデル。Pathways基盤の事前学習モデル。', 2, 'g-kentei'),
    ('phi-model', 'Phi', 'Phi', 'P', 'Microsoftの小型高性能オープンウェイトLLMファミリー。', 2, 'g-kentei'),
    ('pointnet', 'PointNet', 'PointNet', 'P', '点群を直接処理する深層学習アーキテクチャ。', 2, 'g-kentei'),
    ('pytorch', 'PyTorch', 'PyTorch', 'P', '動的グラフが特徴の深層学習フレームワーク。', 2, 'g-kentei'),
    ('qlora', 'QLoRA', 'QLoRA', 'Q', '量子化とLoRAを組み合わせた省メモリ微調整。', 2, 'g-kentei'),
    ('qwen', 'Qwen', 'Qwen', 'Q', 'Alibabaの多言語対応オープンウェイトLLMファミリー。', 2, 'g-kentei'),
    ('rcnn', 'R-CNN', 'R-CNN', 'R', '領域提案とCNN分類を組み合わせた検出の先駆手法。', 2, 'g-kentei'),
    ('rmsprop', 'RMSprop', 'RMSprop', 'R', '勾配二乗の移動平均で学習率を調整する最適化。', 2, 'g-kentei'),
    ('rnn', 'RNN', '再帰型ニューラルネットワーク', '', '時系列データや文章など順序のあるデータの処理に特化したニューラルネットワーク。LSTMはその代表的な改良版。', 2, 'g-kentei'),
    ('rouge', 'ROUGE', 'ROUGE', 'R', '要約のn-gram再現に基づく評価指標。', 2, 'g-kentei'),
    ('relu', 'ReLU', 'Rectified Linear Unit', 'R', '負値を0にする単純な活性化関数。深層学習で最も広く使われる。', 2, 'g-kentei'),
    ('resnet', 'ResNet', 'Residual Network', 'R', '残差接続で非常に深いネットを学習可能にしたCNN。', 2, 'g-kentei'),
    ('roberta', 'RoBERTa', 'RoBERTa', 'R', 'BERTの学習手順を改良したモデル。', 2, 'g-kentei'),
    ('rotary-position-embedding', 'RoPE', 'Rotary Position Embedding', 'R', '回転で位置情報を埋め込む手法。LLMで広く採用。', 2, 'g-kentei'),
    ('sam2', 'SAM 2', 'Segment Anything Model 2', 'S', '画像・動画の汎用セグメンテーションモデル。', 2, 'g-kentei'),
    ('sdxl', 'SDXL', 'Stable Diffusion XL', 'S', 'Stable Diffusionの高解像度・高品質版モデル。', 2, 'g-kentei'),
    ('squeeze-and-excitation', 'SEブロック', 'Squeeze-and-Excitation', 'S', 'チャネル間の依存を学習し特徴を再重み付け。', 2, 'g-kentei'),
    ('sft', 'SFT', 'Supervised Fine-Tuning', 'S', '教師データで言語モデルを指示追従向けに微調整。', 2, 'g-kentei|genai-passport'),
    ('sgd', 'SGD', 'Stochastic Gradient Descent', 'S', 'ミニバッチで勾配降下する基本最適化手法。', 2, 'g-kentei'),
    ('sift', 'SIFT', 'Scale-Invariant Feature Transform', 'S', 'スケール不変な局所特徴記述子。', 2, 'g-kentei'),
    ('slam', 'SLAM', 'Simultaneous Localization and Mapping', 'S', '自己位置推定と地図構築を同時に行う技術。', 2, 'g-kentei'),
    ('ssd', 'SSD', 'Single Shot Detector', 'S', 'マルチスケール特徴で一発検出するモデル。', 2, 'g-kentei'),
    ('segment-anything', 'Segment Anything', 'Segment Anything', 'S', 'プロンプトで任意物体をセグメントする基盤モデル。', 2, 'g-kentei'),
    ('sentencepiece', 'SentencePiece', 'SentencePiece', 'S', '言語非依存のサブワードトークナイザ実装。', 2, 'g-kentei'),
    ('seq2seq', 'Seq2Seq', 'Sequence to Sequence', 'S', '系列を別系列へ写すエンコーダ・デコーダ枠組み。', 2, 'g-kentei'),
    ('simclr', 'SimCLR', 'SimCLR', 'S', 'データ拡張と対照損失による自己教師あり学習。', 2, 'g-kentei'),
    ('sora-model', 'Sora', 'Sora', 'S', 'OpenAIのテキストから動画を生成する拡散トランスフォーマーモデル。', 2, 'g-kentei|genai-passport'),
    ('stable-diffusion', 'Stable Diffusion', 'Stable Diffusion', 'S', '潜在拡散によるオープンなテキスト画像生成モデル。', 2, 'g-kentei|genai-passport'),
    ('structure-from-motion', 'Structure from Motion', 'Structure from Motion', 'S', '複数画像から3D構造とカメラ姿勢を復元する。', 2, 'g-kentei'),
    ('stylegan', 'StyleGAN', 'StyleGAN', 'S', '高品質顔画像生成で知られるGANファミリー。', 2, 'g-kentei'),
    ('swin-transformer', 'Swin Transformer', 'Swin Transformer', 'S', '階層的ウィンドウ注意を用いる画像Transformer。', 2, 'g-kentei'),
    ('t5-model', 'T5', 'Text-to-Text Transfer Transformer', 'T', '全NLPタスクをテキスト変換として統一するモデル。', 2, 'g-kentei'),
    ('tcn', 'TCN', 'Temporal Convolutional Network', 'T', '因果的畳み込みで長系列を扱うネット。', 2, 'g-kentei'),
    ('tf-idf', 'TF-IDF', 'TF-IDF', 'T', '語の重要度を文書頻度で重み付けする手法。', 2, 'g-kentei'),
    ('tensorflow', 'TensorFlow', 'TensorFlow', 'T', 'Google製の深層学習フレームワーク。', 2, 'g-kentei'),
    ('tensorrt', 'TensorRT', 'TensorRT', 'T', 'NVIDIAの推論最適化ランタイム。', 2, 'g-kentei'),
    ('text-to-sql', 'Text-to-SQL', 'Text-to-SQL', 'T', '自然言語の質問をSQLクエリに変換するタスク。', 2, 'g-kentei|genai-passport'),
    ('transformer', 'Transformer', 'トランスフォーマー', '', '現代の大規模言語モデルの基盤となるアーキテクチャ。アテンション機構により長距離の依存関係を効率的に学習できる。', 2, 'g-kentei'),
    ('transformer-block', 'Transformerブロック', 'Transformer Block', 'T', '注意層とFFN・正規化・残差からなる基本単位。', 2, 'g-kentei'),
    ('triplet-loss', 'Triplet Loss', 'Triplet Loss', 'T', 'アンカー・正例・負例の距離関係を学習する損失。', 2, 'g-kentei'),
    ('unet', 'U-Net', 'U-Net', 'U', 'エンコーダ・デコーダ構造の画像セグメンテーションネット。', 2, 'g-kentei'),
    ('u-net-architecture', 'U-Net構造', 'U-Net Architecture', 'U', 'スキップ接続付きエンコーダ・デコーダのセグメント構造。', 2, 'g-kentei'),
    ('ulmfit', 'ULMFiT', 'ULMFiT', 'U', '言語モデル微調整による転移学習フレームワーク。', 3, 'g-kentei'),
    ('unigram-language-model-tokenizer', 'Unigram言語モデル', 'Unigram Language Model', 'U', '確率言語モデルに基づくサブワードトークナイザ。', 2, 'g-kentei'),
    ('vgg', 'VGG', 'VGG', 'V', '小さな畳み込みを重ねた古典的深いCNNアーキテクチャ。', 2, 'g-kentei'),
    ('vision-transformer-patch', 'ViTパッチ', 'ViT Patch', 'V', '画像を固定サイズパッチに分割してTransformer入力にする。', 2, 'g-kentei'),
    ('vision-transformer', 'Vision Transformer', 'ViT', 'V', '画像をパッチ列としてTransformerで処理するモデル。', 2, 'g-kentei'),
    ('wasserstein-gan', 'WGAN', 'Wasserstein GAN', 'W', 'Wasserstein距離でGAN学習を安定化。', 3, 'g-kentei'),
    ('wavenet', 'WaveNet', 'WaveNet', 'W', '拡張畳み込みで高品質音声を生成するモデル。', 2, 'g-kentei'),
    ('whisper-model', 'Whisper', 'Whisper', 'W', 'OpenAIの多言語音声認識・翻訳モデル。', 2, 'g-kentei|genai-passport'),
    ('word2vec', 'Word2Vec', 'Word2Vec', 'W', '周辺語予測で単語埋め込みを学習する手法。', 2, 'g-kentei'),
    ('xlnet', 'XLNet', 'XLNet', 'X', '順列言語モデリングを用いた大規模言語モデル。', 2, 'g-kentei'),
    ('xavier-initialization', 'Xavier初期化', 'Xavier Initialization', 'X', 'シグモイド・tanh向けの分散調整初期化。', 2, 'g-kentei'),
    ('yolo', 'YOLO', 'You Only Look Once', 'Y', '一発推論で物体検出を行う高速モデルファミリー。', 2, 'g-kentei'),
    ('zero-redundancy-optimizer', 'ZeRO', 'Zero Redundancy Optimizer', 'Z', 'オプティマイザ状態を分散しメモリを削減。', 2, 'g-kentei'),
    ('fasttext', 'fastText', 'fastText', 'f', 'サブワード情報を使う単語表現学習。', 2, 'g-kentei'),
    ('pix2pix', 'pix2pix', 'pix2pix', 'p', '条件付きGANによる画像変換フレームワーク。', 2, 'g-kentei'),
    ('spacy', 'spaCy', 'spaCy', 's', '高速なNLPパイプラインライブラリ。', 2, 'g-kentei'),
    ('tanh', 'tanh', 'Hyperbolic Tangent', 't', '出力を-1〜1に写す活性化関数。', 2, 'g-kentei'),
    ('adapter-tuning', 'アダプタチューニング', 'Adapter Tuning', 'あ', '固定モデルに小さな層を挿入して微調整する手法。', 2, 'g-kentei'),
    ('adapter', 'アダプター', 'Adapter', 'あ', '固定モデルに小さな層を挿入して微調整する手法。', 2, 'g-kentei'),
    ('attention-map', 'アテンションマップ', 'Attention Map', 'あ', '注意重みを可視化したヒートマップ。', 2, 'g-kentei'),
    ('attention', 'アテンション機構', 'Attention Mechanism', '', 'モデルが入力の中で「どこに注目すべきか」を学習する仕組み。Transformerの中核技術であり、翻訳や要約の精度向上に大きく貢献した。', 2, 'g-kentei'),
    ('annotation', 'アノテーション', 'Annotation', 'あ', 'テキストにラベルやタグを付与する作業。', 2, 'g-kentei'),
    ('alignment', 'アライメント', 'Alignment', 'あ', 'AIの目的を人間の意図・価値に整合させること。', 1, 'g-kentei|genai-passport'),
    ('hourglass-network', 'アワーグラスネットワーク', 'Hourglass Network', 'あ', '対称構造で姿勢推定等に使われるネット。', 2, 'g-kentei'),
    ('anchor-box', 'アンカーボックス', 'Anchor Box', 'あ', '物体検出で事前定義した基準ボックス。', 2, 'g-kentei'),
    ('event-extraction', 'イベント抽出', 'Event Extraction', 'い', '文から出来事と参加者を構造化して抽出する。', 2, 'g-kentei'),
    ('instance-segmentation', 'インスタンスセグメンテーション', 'Instance Segmentation', 'い', '個々の物体インスタンスを分離してセグメントする。', 2, 'g-kentei'),
    ('instance-normalization', 'インスタンス正規化', 'Instance Normalization', 'い', '各サンプル内で正規化。スタイル変換で使われる。', 2, 'g-kentei'),
    ('inception-module', 'インセプションモジュール', 'Inception Module', 'い', '多スケール畳み込みを並列化するCNNモジュール。', 2, 'g-kentei'),
    ('warmup', 'ウォームアップ', 'Warmup', 'う', '学習初期に学習率を徐々に上げる技法。大規模学習で有効。', 2, 'g-kentei'),
    ('edge-detection', 'エッジ検出', 'Edge Detection', 'え', '画像内の輪郭・境界を検出する処理。', 2, 'g-kentei'),
    ('encoder-only', 'エンコーダのみモデル', 'Encoder-only Model', 'え', '双方向文脈を扱うTransformer。BERTなど。', 2, 'g-kentei'),
    ('encoder-decoder', 'エンコーダ・デコーダ', 'Encoder-Decoder', 'え', '入力を符号化し別表現へ復号する汎用アーキテクチャ。', 2, 'g-kentei'),
    ('optical-flow', 'オプティカルフロー', 'Optical Flow', 'お', '連続フレーム間のピクセル移動を推定する。', 2, 'g-kentei'),
    ('autoencoder', 'オートエンコーダ', 'Autoencoder', 'お', '入力を圧縮・復元し潜在表現を学ぶネット。', 2, 'g-kentei'),
    ('open-weights', 'オープンウェイト', 'Open Weights', 'お', 'モデル重みが公開・利用可能なモデル。', 2, 'g-kentei|genai-passport'),
    ('camera-calibration', 'カメラキャリブレーション', 'Camera Calibration', 'か', 'カメラの内部・外部パラメータを推定する。', 2, 'g-kentei'),
    ('convolution-kernel', 'カーネル（画像）', 'Convolution Kernel', 'か', '畳み込みで使う小さなフィルタ行列。', 2, 'g-kentei'),
    ('keypoint-detection', 'キーポイント検出', 'Keypoint Detection', 'き', '画像上の特徴的な点を検出するタスク。', 2, 'g-kentei'),
    ('keyword-extraction', 'キーワード抽出', 'Keyword Extraction', 'き', '文書から重要語を自動抽出するタスク。', 2, 'g-kentei'),
    ('cross-attention', 'クロスアテンション', 'Cross-Attention', 'く', '異なる系列間で注意を計算する機構。条件付き生成に利用。', 2, 'g-kentei'),
    ('cross-lingual', 'クロスリンガル', 'Cross-lingual', 'く', '言語をまたいで知識や表現を転用する手法。', 2, 'g-kentei'),
    ('closed-model', 'クローズドモデル', 'Closed Model', 'く', '重み非公開でAPI等のみ提供されるモデル。', 2, 'g-kentei|genai-passport'),
    ('graph-neural-network', 'グラフニューラルネットワーク', 'Graph Neural Network', 'ぐ', 'グラフ構造データを扱う深層学習。', 2, 'g-kentei'),
    ('group-normalization', 'グループ正規化', 'Group Normalization', 'ぐ', 'チャネルをグループ化して正規化する手法。', 2, 'g-kentei'),
    ('grayscale', 'グレースケール', 'Grayscale', 'ぐ', '色情報を除去し輝度のみで表現する画像。', 2, 'g-kentei'),
    ('global-average-pooling', 'グローバル平均プーリング', 'Global Average Pooling', 'ぐ', '特徴マップ全体の平均を取るプーリング。', 2, 'g-kentei'),
    ('cosine-similarity', 'コサイン類似度', 'Cosine Similarity', 'こ', 'ベクトル間の角度に基づく類似度指標。', 2, 'g-kentei'),
    ('connectionism', 'コネクショニズム', 'Connectionism', 'こ', 'ニューラルネットワークで知識を分布表現するアプローチ。現代DLの源流。', 2, 'g-kentei'),
    ('collocation', 'コロケーション', 'Collocation', 'こ', '一緒に使われやすい語の組み合わせ。', 2, 'g-kentei'),
    ('context-window', 'コンテキストウィンドウ', 'Context Window', 'こ', 'モデルが一度に処理できるトークン数の上限。', 2, 'g-kentei|genai-passport'),
    ('corner-detection', 'コーナー検出', 'Corner Detection', 'こ', '画像上の角点を検出する古典的処理。', 2, 'g-kentei'),
    ('corpus', 'コーパス', 'Corpus', 'こ', '言語研究・学習用に整備された大規模テキスト集合。', 2, 'g-kentei'),
    ('subword', 'サブワード', 'Subword', 'さ', '語彙外語を小さな単位で表現する語彙設計。', 2, 'g-kentei'),
    ('subword-tokenization', 'サブワードトークン化', 'Subword Tokenization', 'さ', '語彙外語をサブ単位で表現する分割方式。BPEなど。', 2, 'g-kentei'),
    ('subword-regularization', 'サブワード正則化', 'Subword Regularization', 'さ', 'トークン分割の揺らぎで頑健性を高める手法。', 2, 'g-kentei'),
    ('sigmoid', 'シグモイド関数', 'Sigmoid', 'し', '出力を0〜1に写すS字状活性化関数。', 2, 'g-kentei'),
    ('siamese-network', 'シャムネットワーク', 'Siamese Network', 'し', '同一構造の2ブランチで類似度を学習するネット。', 2, 'g-kentei'),
    ('scene-understanding', 'シーン理解', 'Scene Understanding', 'し', '画像全体の状況・関係性を理解するタスク。', 2, 'g-kentei'),
    ('gesture-recognition', 'ジェスチャ認識', 'Gesture Recognition', 'じ', '手や体の動きを認識するタスク。', 2, 'g-kentei'),
    ('skip-connection', 'スキップ接続', 'Skip Connection', 'す', '層を飛び越え勾配と情報を直接伝える接続。ResNetなど。', 2, 'g-kentei'),
    ('stemming', 'ステミング', 'Stemming', 'す', '語尾を切り落として語幹に正規化する粗い手法。', 2, 'g-kentei'),
    ('stereo-vision', 'ステレオ視', 'Stereo Vision', 'す', '複数カメラの視差から深度を復元する。', 2, 'g-kentei'),
    ('stop-words', 'ストップワード', 'Stop Words', 'す', '検索や解析で除外する高頻度かつ低情報語。', 2, 'g-kentei'),
    ('stride', 'ストライド', 'Stride', 'す', '畳み込みやプーリングの移動幅。', 2, 'g-kentei'),
    ('sparse-attention', 'スパースアテンション', 'Sparse Attention', 'す', '注意計算の一部だけを計算してコストを削減。', 2, 'g-kentei'),
    ('spectral-normalization', 'スペクトル正規化', 'Spectral Normalization', 'す', '重みのスペクトルノルムを制限しGAN等を安定化。', 2, 'g-kentei'),
    ('spectrogram', 'スペクトログラム', 'Spectrogram', 'す', '音声の時間・周波数表現。音響モデルの入力に使う。', 2, 'g-kentei'),
    ('spell-checking', 'スペルチェック', 'Spell Checking', 'す', '誤字脱字を検出・修正する機能。', 2, 'g-kentei'),
    ('rubber-band-attention', 'スライディングウィンドウ注意', 'Sliding Window Attention', 'す', '局所ウィンドウ内だけに注意を限定する手法。', 2, 'g-kentei'),
    ('slot-filling', 'スロットフィリング', 'Slot Filling', 'す', '対話で必要なパラメータ値を抽出する。', 2, 'g-kentei'),
    ('semantic-segmentation', 'セマンティックセグメンテーション', 'Semantic Segmentation', 'せ', 'ピクセルごとにクラスラベルを付与するタスク。', 2, 'g-kentei'),
    ('softmax', 'ソフトマックス', 'Softmax', 'そ', '多クラス分類の出力を確率分布に変換する関数。', 2, 'g-kentei'),
    ('checkpointing', 'チェックポイント', 'Checkpointing', 'ち', '学習途中のモデル状態を保存・再開する仕組み。', 2, 'g-kentei'),
    ('chatbot', 'チャットボット', 'Chatbot', 'ち', 'テキスト会話で問い合わせ等に応答するボット。', 2, 'g-kentei|genai-passport'),
    ('channel-attention', 'チャネル注意', 'Channel Attention', 'ち', 'どの特徴チャネルが重要かを学習する注意。', 2, 'g-kentei'),
    ('teacher-forcing', 'ティーチャーフォーシング', 'Teacher Forcing', 'て', 'デコーダ学習時に正解系列を入力として与える技法。', 2, 'g-kentei'),
    ('text-segmentation', 'テキスト分割', 'Text Segmentation', 'て', '長文を意味のある単位に区切る処理。', 2, 'g-kentei'),
    ('text-classification', 'テキスト分類', 'Text Classification', 'て', '文書や文をカテゴリに分類するタスク。', 2, 'g-kentei'),
    ('text-normalization', 'テキスト正規化', 'Text Normalization', 'て', '表記ゆれやノイズを統一する前処理。', 2, 'g-kentei'),
    ('text-generation', 'テキスト生成', 'Text Generation', 'て', 'モデルが新しい自然言語文を生成するタスク。', 2, 'g-kentei|genai-passport'),
    ('text-summarization', 'テキスト要約', 'Text Summarization', 'て', '長文の要点を短い文に圧縮するタスク。', 2, 'g-kentei'),
    ('tensor-parallelism', 'テンソル並列', 'Tensor Parallelism', 'て', '層内の行列を分割して巨大モデルを分散保持。', 2, 'g-kentei'),
    ('template-matching', 'テンプレートマッチング', 'Template Matching', 'て', '基準パターンとの類似で位置を探す古典的手法。', 2, 'g-kentei'),
    ('deep-learning', 'ディープラーニング', 'Deep Learning', '', '多層のニューラルネットワークを使った機械学習の手法。画像・音声・自然言語など幅広い分野で高い精度を発揮する。', 2, 'g-kentei'),
    ('decoder-only', 'デコーダのみモデル', 'Decoder-only Model', 'で', '自己回帰生成に特化したTransformer。GPTなど。', 2, 'g-kentei'),
    ('data-parallel', 'データ並列', 'Data Parallelism', 'で', '同一モデルを複製しデータを分割して学習。', 2, 'g-kentei'),
    ('topic-modeling', 'トピックモデル', 'Topic Modeling', 'と', '文書集合から潜在トピックを抽出する手法。LDAなど。', 2, 'g-kentei'),
    ('tokenization', 'トークン化', 'Tokenization', 'と', 'テキストをモデルが扱う単位へ分割する処理。', 2, 'g-kentei|genai-passport'),
    ('document-ai', 'ドキュメントAI', 'Document AI', 'ど', '帳票・文書画像の読取・構造化を行うAI。', 2, 'g-kentei'),
    ('domain-randomization', 'ドメインランダム化', 'Domain Randomization', 'ど', 'シミュレーション多様化で実世界への汎化を促す。', 2, 'g-kentei'),
    ('domain-adaptation', 'ドメイン適応', 'Domain Adaptation', 'ど', '学習域と運用域の分布差を吸収する転移手法。', 2, 'g-kentei'),
    ('dropout', 'ドロップアウト', 'Dropout', '', '学習中にランダムにニューロンを無効化することで過学習を防ぐ手法。汎化性能の向上に効果がある。', 2, 'g-kentei'),
    ('neural-network', 'ニューラルネットワーク', 'Neural Network', '', '人間の脳の神経回路を模した計算モデル。層を重ねることで複雑なパターンを学習できる。', 2, 'g-kentei'),
    ('neural-language-model', 'ニューラル言語モデル', 'Neural Language Model', 'に', 'ニューラルネットで言語確率を学習するモデル。', 2, 'g-kentei'),
    ('denoising-diffusion', 'ノイズ除去拡散', 'Denoising Diffusion', 'の', '段階的にノイズを除去してサンプルを生成する手法。', 2, 'g-kentei'),
    ('highway-network', 'ハイウェイネットワーク', 'Highway Network', 'は', 'ゲート付きスキップ接続で深いネットを学習。', 2, 'g-kentei'),
    ('harris-corner', 'ハリスコーナー', 'Harris Corner', 'は', '勾配から角点を検出する代表的手法。', 2, 'g-kentei'),
    ('byte-pair-encoding', 'バイトペアエンコーディング', 'Byte Pair Encoding', 'ば', 'BPEの正式名称。サブワード語彙構築手法。', 2, 'g-kentei'),
    ('bounding-box', 'バウンディングボックス', 'Bounding Box', 'ば', '物体の位置を矩形で表す表現。', 2, 'g-kentei'),
    ('batch-normalization', 'バッチ正規化', 'Batch Normalization', 'ば', 'ミニバッチ統計で各層の入力分布を安定化する技法。', 2, 'g-kentei'),
    ('barcode-recognition', 'バーコード認識', 'Barcode Recognition', 'ば', 'バーコード・QRコードを画像から読み取る。', 2, 'g-kentei'),
    ('pipeline-parallelism', 'パイプライン並列', 'Pipeline Parallelism', 'ぱ', '層をデバイスに分割しパイプライン実行する。', 2, 'g-kentei'),
    ('padding', 'パディング', 'Padding', 'ぱ', '入力周辺に値を付加し出力サイズや境界を制御する。', 2, 'g-kentei'),
    ('panorama', 'パノラマ画像', 'Panorama', 'ぱ', '広い視野を一枚に合成した画像。', 2, 'g-kentei'),
    ('perplexity', 'パープレキシティ', 'Perplexity', 'ぱ', '言語モデルの予測不確実性を測る指標。低いほど良い。', 2, 'g-kentei'),
    ('histogram-equalization', 'ヒストグラム均等化', 'Histogram Equalization', 'ひ', '輝度分布を均すことでコントラストを改善する。', 2, 'g-kentei'),
    ('hinge-loss', 'ヒンジ損失', 'Hinge Loss', 'ひ', 'マージンを確保する分類損失。SVMで使われる。', 2, 'g-kentei'),
    ('beam-search', 'ビームサーチ', 'Beam Search', 'び', '上位候補のみを保持する近似探索。翻訳・生成で使用。', 2, 'g-kentei'),
    ('fine-tuning', 'ファインチューニング', 'Fine-tuning', '', '事前学習済みモデルを特定のタスクや用途向けに追加学習させること。少ないデータで高い精度を達成できる。', 2, 'g-kentei'),
    ('feed-forward-network', 'フィードフォワードネット', 'Feed-Forward Network', 'ふ', 'Transformerブロック内の位置ごとの全結合サブ層。', 2, 'g-kentei'),
    ('full-fine-tuning', 'フルファインチューニング', 'Full Fine-tuning', 'ふ', 'モデル全パラメータを更新する微調整。', 2, 'g-kentei|genai-passport'),
    ('prefix-tuning', 'プレフィックストゥーニング', 'Prefix Tuning', 'ぷ', '入力前に学習可能ベクトルを付加して制御する微調整。', 2, 'g-kentei'),
    ('pooling', 'プーリング', 'Pooling', 'ぷ', '特徴マップをダウンサンプリングし位置不変性を高める。', 2, 'g-kentei'),
    ('homography', 'ホモグラフィ', 'Homography', 'ほ', '平面間の射影変換を表す行列。', 2, 'g-kentei'),
    ('masked-language-model', 'マスク言語モデル', 'Masked Language Model', 'ま', '文中のマスク語を予測する事前学習方式。BERTなど。', 2, 'g-kentei'),
    ('max-pooling', 'マックスプーリング', 'Max Pooling', 'ま', '領域内最大値を取るプーリング。', 2, 'g-kentei'),
    ('multi-head-attention', 'マルチヘッドアテンション', 'Multi-Head Attention', 'ま', '複数の注意を並列計算し多様な関係を捉える。', 2, 'g-kentei'),
    ('multimodal-ai', 'マルチモーダルAI', 'Multimodal AI', '', 'テキスト・画像・音声など複数の形式のデータを同時に処理できるAI。GPT-4oやGeminiなどが対応している。', 2, 'g-kentei'),
    ('mel-spectrogram', 'メルスペクトログラム', 'Mel Spectrogram', 'め', '人間の聴覚に近い周波数スケールのスペクトログラム。', 2, 'g-kentei'),
    ('model-card', 'モデルカード', 'Model Card', 'も', 'モデルの用途・限界・評価を文書化した説明資料。', 2, 'g-kentei|genai-passport'),
    ('model-merging', 'モデルマージ', 'Model Merging', 'も', '複数モデルの重みを合成して新モデルを作る手法。', 2, 'g-kentei'),
    ('model-parallel', 'モデル並列', 'Model Parallelism', 'も', '巨大モデルを複数デバイスに分割して保持。', 2, 'g-kentei'),
    ('morphological-filter', 'モルフォロジー演算', 'Morphological Operations', 'も', '膨張・収縮など形状ベースの画像処理。', 2, 'g-kentei'),
    ('mode-collapse', 'モード崩壊', 'Mode Collapse', 'も', 'GANが多様性を失い似た出力ばかり生成する問題。', 2, 'g-kentei'),
    ('momentum', 'モーメンタム', 'Momentum', 'も', '過去勾配の慣性で更新を加速するSGD拡張。', 2, 'g-kentei'),
    ('label-smoothing', 'ラベルスムージング', 'Label Smoothing', 'ら', '正解ラベルを少し柔らかくし過信を防ぐ正則化。', 2, 'g-kentei'),
    ('remote-sensing', 'リモートセンシング', 'Remote Sensing', 'り', 'センサーから離れた対象を観測・解析する技術。', 2, 'g-kentei'),
    ('layer-normalization', 'レイヤー正規化', 'Layer Normalization', 'れ', '層内の特徴次元で正規化。Transformerで標準的。', 2, 'g-kentei'),
    ('pretraining', '事前学習', 'Pretraining', 'じ', '大規模コーパスで言語や表現の基礎を学ぶ段階。', 2, 'g-kentei'),
    ('pretrained-model', '事前学習モデル', 'Pretrained Model', 'じ', '大規模データで学習済みの公開モデル。', 2, 'g-kentei'),
    ('mean-squared-error-loss', '二乗誤差損失', 'MSE Loss', 'に', '回帰の標準損失。', 2, 'g-kentei'),
    ('cross-entropy-loss', '交差エントロピー損失', 'Cross-Entropy Loss', 'こ', '分類で最も広く使われる損失関数。', 2, 'g-kentei'),
    ('positional-encoding', '位置エンコーディング', 'Positional Encoding', 'い', 'Transformerに単語順序情報を与える技法。', 2, 'g-kentei'),
    ('dependency-parsing', '係り受け解析', 'Dependency Parsing', 'か', '文内の単語間の文法依存関係を分析する。', 2, 'g-kentei'),
    ('fully-connected-layer', '全結合層', 'Fully Connected Layer', 'ぜ', '全入力ニューロンと結合する基本層。MLPの構成要素。', 2, 'g-kentei'),
    ('coreference-resolution', '共参照解消', 'Coreference Resolution', 'き', '代名詞等が同じ実体を指すかを解決する。', 2, 'g-kentei'),
    ('co-occurrence', '共起', 'Co-occurrence', 'き', '語や特徴が同時に現れる関係。', 2, 'g-kentei'),
    ('word-segmentation', '分かち書き', 'Word Segmentation', 'わ', '境界のない言語で語境界を決める処理。', 2, 'g-kentei'),
    ('distributed-training', '分散学習', 'Distributed Training', 'ぶ', '複数GPU・ノードで大規模学習を行う方式。', 2, 'g-kentei'),
    ('pruning', '剪定', 'Pruning', 'せ', '不要な重みやニューロンを除去してモデルを軽量化。', 2, 'g-kentei'),
    ('video-understanding', '動画理解', 'Video Understanding', 'ど', '時系列映像から行動やイベントを認識する領域。', 2, 'g-kentei'),
    ('dynamic-quantization', '動的量子化', 'Dynamic Quantization', 'ど', '推論時に動的に量子化して高速化する技法。', 2, 'g-kentei'),
    ('gradient-clipping', '勾配クリッピング', 'Gradient Clipping', 'こ', '勾配爆発を防ぐため勾配ノルムや値を制限する。', 2, 'g-kentei'),
    ('gradient-checkpointing', '勾配チェックポイント', 'Gradient Checkpointing', 'こ', '中間活性を捨て再計算しメモリを節約する技法。', 2, 'g-kentei'),
    ('vanishing-gradient', '勾配消失', 'Vanishing Gradient', 'こ', '深いネットで勾配が小さくなり学習が進まない問題。', 2, 'g-kentei'),
    ('exploding-gradient', '勾配爆発', 'Exploding Gradient', 'こ', '勾配が際限なく大きくなり学習が不安定になる問題。', 2, 'g-kentei'),
    ('gradient-accumulation', '勾配蓄積', 'Gradient Accumulation', 'こ', '小バッチを蓄積し実効バッチを大きくする技法。', 2, 'g-kentei'),
    ('medical-imaging', '医用画像', 'Medical Imaging', 'い', 'X線・CT・MRI等の診断画像をAIで解析する領域。', 2, 'g-kentei'),
    ('word-embedding', '単語埋め込み', 'Word Embedding', 'た', '単語を密なベクトルで表現する技術。', 2, 'g-kentei'),
    ('bidirectional-rnn', '双方向RNN', 'Bidirectional RNN', 'そ', '過去と未来の文脈を同時に参照するRNN。', 2, 'g-kentei'),
    ('receptive-field', '受容野', 'Receptive Field', 'じ', '出力ニューロンが参照する入力領域の広さ。', 2, 'g-kentei'),
    ('synthetic-data', '合成データ', 'Synthetic Data', 'ご', 'シミュレーションや生成モデルで作った学習データ。', 2, 'g-kentei'),
    ('part-of-speech', '品詞', 'Part of Speech', 'ひ', '名詞・動詞など単語の文法的カテゴリ。', 2, 'g-kentei'),
    ('pos-tagging', '品詞タグ付け', 'Part-of-Speech Tagging', 'ひ', '各単語に品詞ラベルを付与するタスク。', 2, 'g-kentei'),
    ('rotated-object-detection', '回転物体検出', 'Rotated Object Detection', 'か', '任意角度のバウンディングボックスで物体を検出。', 2, 'g-kentei'),
    ('causal-language-model', '因果的言語モデル', 'Causal Language Model', 'い', '過去のみから次トークンを予測する自己回帰モデル。', 2, 'g-kentei'),
    ('named-entity-linking', '固有表現リンク', 'Named Entity Linking', 'こ', '抽出した固有表現を知識ベースの項目へ結び付ける。', 2, 'g-kentei'),
    ('named-entity-recognition', '固有表現抽出', 'Named Entity Recognition', 'こ', '人名・地名・組織名などを文から検出するタスク。', 2, 'g-kentei'),
    ('embedding-model', '埋め込みモデル', 'Embedding Model', 'う', 'テキスト等をベクトル化する専用モデル。', 2, 'g-kentei|genai-passport'),
    ('reward-model', '報酬モデル', 'Reward Model', 'ほ', '回答の質をスカラーで評価するモデル。RLHFで使用。', 2, 'g-kentei'),
    ('variational-autoencoder', '変分オートエンコーダ', 'Variational Autoencoder', 'へ', '潜在空間を確率分布でモデル化する生成モデル。', 2, 'g-kentei'),
    ('visual-inspection', '外観検査', 'Visual Inspection', 'が', '製造ライン等で画像により不良を検出する。', 2, 'g-kentei'),
    ('mlp', '多層パーセプトロン', 'Multilayer Perceptron', 'た', '全結合層を積み重ねた基本的深層ネット。', 2, 'g-kentei'),
    ('multilingual-nlp', '多言語NLP', 'Multilingual NLP', 'た', '複数言語を横断して処理する自然言語技術。', 2, 'g-kentei'),
    ('pose-estimation', '姿勢推定', 'Pose Estimation', 'し', '人体や物体の関節位置を推定するタスク。', 2, 'g-kentei'),
    ('learning-rate-scheduler', '学習率スケジューラ', 'Learning Rate Scheduler', 'が', '学習の進行に応じて学習率を変化させる仕組み。', 2, 'g-kentei'),
    ('contrastive-learning', '対照学習', 'Contrastive Learning', 'た', '正例を近づけ負例を遠ざける表現学習。', 2, 'g-kentei'),
    ('contrastive-loss', '対照損失', 'Contrastive Loss', 'た', '正例を近づけ負例を遠ざける損失関数。', 2, 'g-kentei'),
    ('parallel-corpus', '対訳コーパス', 'Parallel Corpus', 'た', '原文と訳文が対応づいた翻訳学習用データ。', 2, 'g-kentei'),
    ('dialogue-system', '対話システム', 'Dialogue System', 'た', 'ユーザーと自然な会話を行うシステム。', 2, 'g-kentei'),
    ('dialogue-state-tracking', '対話状態追跡', 'Dialogue State Tracking', 'た', '対話のスロット値を更新し文脈を管理する。', 2, 'g-kentei'),
    ('average-pooling', '平均プーリング', 'Average Pooling', 'へ', '領域内平均を取るプーリング。', 2, 'g-kentei'),
    ('morphological-analysis', '形態素解析', 'Morphological Analysis', 'け', '文を意味を持つ最小単位（形態素）に分割する処理。', 2, 'g-kentei'),
    ('response-generation', '応答生成', 'Response Generation', 'お', '対話システムがユーザーへの返答文を生成する。', 2, 'g-kentei'),
    ('information-retrieval', '情報検索', 'Information Retrieval', 'じ', 'クエリに関連する文書を大規模コーパスから探す。', 2, 'g-kentei'),
    ('semantic-parsing', '意味解析', 'Semantic Parsing', 'い', '自然言語を論理式やAPI呼び出しに変換する。', 2, 'g-kentei'),
    ('semantic-similarity', '意味類似度', 'Semantic Similarity', 'い', '文や語の意味的な近さを数値化する。', 2, 'g-kentei'),
    ('intent-recognition', '意図認識', 'Intent Recognition', 'い', 'ユーザー発話の目的・意図を分類する。', 2, 'g-kentei'),
    ('sentiment-analysis', '感情分析', 'Sentiment Analysis', 'か', 'テキストのポジティブ・ネガティブ等を判定する。', 2, 'g-kentei'),
    ('handwriting-recognition', '手書き文字認識', 'Handwriting Recognition', 'て', '手書き文字をコンピュータが読み取る技術。', 2, 'g-kentei'),
    ('speculative-decoding', '投機的デコード', 'Speculative Decoding', 'と', '小モデルで草案を作り大モデルで検証し生成を高速化。', 2, 'g-kentei'),
    ('extractive-summarization', '抽出型要約', 'Extractive Summarization', 'ち', '原文から重要文を選び抜いて要約する方式。', 2, 'g-kentei'),
    ('abstractive-summarization', '抽象型要約', 'Abstractive Summarization', 'ち', '新しい文を生成して要約する方式。', 2, 'g-kentei'),
    ('augmented-reality', '拡張現実', 'Augmented Reality', 'か', '現実映像に仮想情報を重畳する技術。CVと密接。', 2, 'g-kentei'),
    ('dilated-convolution', '拡張畳み込み', 'Dilated Convolution', 'か', '受容野を広げるため穴あき畳み込み。', 2, 'g-kentei'),
    ('instruction-tuning', '指示チューニング', 'Instruction Tuning', 'し', '指示応答データでモデルを会話向けに調整する。', 2, 'g-kentei|genai-passport'),
    ('teacher-student-model', '教師・生徒モデル', 'Teacher-Student Model', 'き', '蒸留で大きな教師と小さな生徒を対にする構成。', 2, 'g-kentei'),
    ('adversarial-example', '敵対例', 'Adversarial Example', 'て', '人には分からない摂動でモデルを誤分類させる入力。', 2, 'g-kentei'),
    ('adversarial-training', '敵対的学習', 'Adversarial Training', 'て', '敵対例で頑健性を高める学習。', 2, 'g-kentei'),
    ('sentence-embedding', '文埋め込み', 'Sentence Embedding', 'ぶ', '文全体を固定長ベクトルで表現する技術。', 2, 'g-kentei'),
    ('document-layout-analysis', '文書レイアウト解析', 'Document Layout Analysis', 'ぶ', '帳票や文書の構造・領域を解析する。', 2, 'g-kentei|genai-passport'),
    ('contextual-embedding', '文脈埋め込み', 'Contextual Embedding', 'ぶ', '文脈に応じて変化する動的な単語表現。', 2, 'g-kentei'),
    ('text-normalization-ja', '日本語正規化', 'Japanese Text Normalization', 'に', '全角半角・表記ゆれを統一する前処理。', 2, 'g-kentei'),
    ('temporal-convolution', '時間畳み込み', 'Temporal Convolution', 'じ', '時系列に1次元畳み込みを適用する手法。', 2, 'g-kentei'),
    ('syntactic-chunking', '構文チャンキング', 'Syntactic Chunking', 'こ', '名詞句などの句単位でテキストを分割するタスク。', 2, 'g-kentei'),
    ('constituency-parsing', '構文解析', 'Constituency Parsing', 'こ', '句や節の階層構造を木として解析する。', 2, 'g-kentei'),
    ('pruning-structured', '構造化剪定', 'Structured Pruning', 'こ', 'チャネルや層単位でモデルを削減する剪定。', 2, 'g-kentei'),
    ('machine-translation', '機械翻訳', 'Machine Translation', 'き', 'ある言語の文を別言語へ自動翻訳する技術。', 2, 'g-kentei'),
    ('residual-connection', '残差接続', 'Residual Connection', 'ざ', '入力に変換差分を足す接続。深いネットの学習を容易にする。', 2, 'g-kentei'),
    ('attention-visualization', '注意可視化', 'Attention Visualization', 'ち', 'モデルがどの語に注目したかを可視化する。', 2, 'g-kentei'),
    ('depthwise-separable-conv', '深度別畳み込み', 'Depthwise Separable Convolution', 'し', 'チャネルごと畳み込み後1x1で結合し計算を削減。', 2, 'g-kentei'),
    ('depth-estimation', '深度推定', 'Depth Estimation', 'し', '単眼画像などから各ピクセルの距離を推定する。', 2, 'g-kentei'),
    ('mixture-of-experts', '混合エキスパート', 'Mixture of Experts', 'こ', '入力ごとに一部の専門サブネットだけを活性化する構造。', 2, 'g-kentei'),
    ('mixed-precision', '混合精度学習', 'Mixed Precision Training', 'こ', 'FP16等を併用し学習を高速化する技法。', 2, 'g-kentei'),
    ('latent-diffusion', '潜在拡散モデル', 'Latent Diffusion', 'せ', '低次元潜在空間で拡散を行い高速化する手法。Stable Diffusionなど。', 2, 'g-kentei'),
    ('point-cloud', '点群', 'Point Cloud', 'て', '3D空間の点集合。LiDARなどの表現形式。', 2, 'g-kentei'),
    ('object-detection', '物体検出', 'Object Detection', 'ぶ', '画像内の物体位置とクラスを同時に予測するタスク。', 2, 'g-kentei'),
    ('object-tracking', '物体追跡', 'Object Tracking', 'ぶ', '動画内で対象物体をフレーム間で追い続ける。', 2, 'g-kentei'),
    ('feature-pyramid', '特徴ピラミッド', 'Feature Pyramid', 'と', '多スケール特徴を統合し検出精度を高める構造。', 2, 'g-kentei'),
    ('feature-map', '特徴マップ', 'Feature Map', 'と', '畳み込み層が出力する空間的特徴表現。', 2, 'g-kentei'),
    ('generative-ai', '生成AI', 'Generative AI', '', 'テキスト・画像・音声・動画など、新しいコンテンツをAIが自動生成する技術の総称。ChatGPTや画像生成AIなど、近年注目を集めるAIの中心ジャンル。', 2, 'g-kentei'),
    ('generative-model', '生成モデル', 'Generative Model', 'せ', 'データの分布そのものを学習し新規サンプルを生成できるモデル。', 2, 'g-kentei'),
    ('generator', '生成器', 'Generator', 'せ', 'GANでデータを生成するネットワーク。', 2, 'g-kentei'),
    ('image-captioning', '画像キャプション', 'Image Captioning', 'が', '画像の内容を自然言語で説明するタスク。', 2, 'g-kentei'),
    ('image-stitching', '画像ステッチング', 'Image Stitching', 'が', '複数画像をつなげてパノラマを作る技術。', 2, 'g-kentei'),
    ('image-segmentation', '画像セグメンテーション', 'Image Segmentation', 'が', 'ピクセルまたは領域単位で画像を分割するタスク。', 2, 'g-kentei'),
    ('image-augmentation', '画像データ拡張', 'Image Augmentation', 'が', '回転・反転などで学習データを人工的に増やす。', 2, 'g-kentei'),
    ('image-denoising', '画像ノイズ除去', 'Image Denoising', 'が', 'ノイズの乗った画像をきれいに復元するタスク。', 2, 'g-kentei'),
    ('image-matching', '画像マッチング', 'Image Matching', 'が', '2画像間の対応点や類似度を求めるタスク。', 2, 'g-kentei'),
    ('image-registration', '画像レジストレーション', 'Image Registration', 'が', '複数画像の位置合わせを行う処理。', 2, 'g-kentei'),
    ('image-processing', '画像処理', 'Image Processing', 'が', '画像のフィルタリング・変換・特徴抽出などの処理全般。', 2, 'g-kentei'),
    ('image-classification', '画像分類', 'Image Classification', 'が', '画像全体を所与クラスに分類するタスク。', 2, 'g-kentei'),
    ('image-retrieval', '画像検索', 'Image Retrieval', 'が', 'クエリ画像やテキストに似た画像を検索する。', 2, 'g-kentei'),
    ('image-super-resolution', '画像超解像', 'Image Super Resolution', 'が', '低解像度画像から高解像度を推定するCVタスク。', 2, 'g-kentei'),
    ('image-quality-assessment', '画質評価', 'Image Quality Assessment', 'が', '画像の鮮明さ・歪みなどを自動評価する。', 2, 'g-kentei'),
    ('convolution', '畳み込み', 'Convolution', 'た', '局所的なパターンを抽出する演算。CNNの核心。', 2, 'g-kentei'),
    ('knowledge-distillation', '知識蒸留', 'Knowledge Distillation', 'ち', '大モデルの知識を小モデルへ移す技法。', 2, 'g-kentei'),
    ('spatial-attention', '空間注意', 'Spatial Attention', 'く', '画像のどの位置に注目するかを学習する注意。', 2, 'g-kentei'),
    ('fine-grained-classification', '細粒度分類', 'Fine-grained Classification', 'さ', '鳥の種など似たクラスを区別する分類。', 2, 'g-kentei'),
    ('statistical-language-model', '統計的言語モデル', 'Statistical Language Model', 'と', 'n-gram等で言語確率をモデル化する古典的手法。', 2, 'g-kentei'),
    ('continued-pretraining', '継続事前学習', 'Continued Pretraining', 'け', 'ドメイン固有データでさらに事前学習を続けること。', 2, 'g-kentei'),
    ('background-subtraction', '背景差分', 'Background Subtraction', 'は', '動画から前景オブジェクトを切り出す手法。', 2, 'g-kentei'),
    ('self-supervised-learning', '自己教師あり学習', 'Self-supervised Learning', 'じ', 'データ自身から疑似ラベルを作り表現を学ぶ手法。LLMの事前学習に多用。', 2, 'g-kentei'),
    ('self-attention', '自己注意', 'Self-Attention', 'じ', '同一系列内の要素同士の関連を重み付けする注意機構。', 2, 'g-kentei'),
    ('natural-language-understanding', '自然言語理解', 'Natural Language Understanding', 'し', 'テキストの意味・意図をコンピュータが理解する能力。', 2, 'g-kentei|genai-passport'),
    ('natural-language-generation', '自然言語生成', 'Natural Language Generation', 'し', 'コンピュータが自然な文章を生成する能力。', 2, 'g-kentei|genai-passport'),
    ('color-space', '色空間', 'Color Space', 'い', 'RGBやHSVなど色を数値で表す座標系。', 2, 'g-kentei'),
    ('knowledge-distillation-temperature', '蒸留温度', 'Distillation Temperature', 'じ', 'ソフトターゲットの平滑化に使う温度パラメータ。', 2, 'g-kentei'),
    ('action-recognition', '行動認識', 'Action Recognition', 'こ', '動画から人の動作やイベントを認識する。', 2, 'g-kentei'),
    ('optical-character-recognition-line', '行認識', 'Line Recognition', 'ぎ', 'OCRの一部。テキスト行の検出と認識。', 2, 'g-kentei'),
    ('satellite-imagery', '衛星画像解析', 'Satellite Imagery Analysis', 'え', '衛星画像から土地利用や災害等を解析する。', 2, 'g-kentei'),
    ('table-question-answering', '表質問応答', 'Table Question Answering', 'ひ', '表データに対する自然言語質問に答えるタスク。', 2, 'g-kentei'),
    ('multi-object-tracking', '複数物体追跡', 'Multi-Object Tracking', 'ふ', '複数対象をフレーム間で一貫して追跡する。', 2, 'g-kentei'),
    ('lemmatization', '見出し語化', 'Lemmatization', 'み', '辞書に基づき単語を基本形へ正規化する。', 2, 'g-kentei'),
    ('vision-language-model', '視覚言語モデル', 'Vision-Language Model', 'し', '画像とテキストを統合処理するマルチモーダルモデル。', 2, 'g-kentei|genai-passport'),
    ('visual-question-answering', '視覚質問応答', 'Visual Question Answering', 'し', '画像と質問から答えを生成するタスク。', 2, 'g-kentei'),
    ('paraphrase', '言い換え', 'Paraphrase', 'い', '意味を保ち表現だけ変えた文のペア。', 2, 'g-kentei'),
    ('paraphrase-detection', '言い換え検出', 'Paraphrase Detection', 'い', '2文が同義かどうかを判定するタスク。', 2, 'g-kentei'),
    ('language-model', '言語モデル', 'Language Model', 'げ', '次の語や文字の確率を予測するモデル。', 2, 'g-kentei'),
    ('language-identification', '言語識別', 'Language Identification', 'げ', 'テキストがどの言語かを判定するタスク。', 2, 'g-kentei'),
    ('evaluation-harness', '評価ハーネス', 'Evaluation Harness', 'ひ', 'モデル性能をベンチマークで測る枠組み。', 2, 'g-kentei'),
    ('vocabulary', '語彙', 'Vocabulary', 'ご', 'モデルや解析器が扱う語・トークンの集合。', 2, 'g-kentei'),
    ('word-sense-disambiguation', '語義曖昧性解消', 'Word Sense Disambiguation', 'ご', '多義語の正しい意味を文脈から決める。', 2, 'g-kentei'),
    ('reading-comprehension', '読解', 'Reading Comprehension', 'ど', '与えられた文章を理解して質問に答えるタスク。', 2, 'g-kentei'),
    ('discriminative-model', '識別モデル', 'Discriminative Model', 'し', 'クラス境界や条件付き確率を直接学習するモデル。', 2, 'g-kentei'),
    ('discriminator', '識別器', 'Discriminator', 'し', 'GANで本物と生成物を見分けるネットワーク。', 2, 'g-kentei'),
    ('question-answering', '質問応答', 'Question Answering', 'し', '質問に対し適切な答えを返すタスク。', 2, 'g-kentei'),
    ('metric-learning', '距離学習', 'Metric Learning', 'き', '類似度空間を直接最適化する学習パラダイム。', 2, 'g-kentei'),
    ('transposed-convolution', '転置畳み込み', 'Transposed Convolution', 'て', 'アップサンプリングに使われる畳み込みの一種。', 2, 'g-kentei'),
    ('contour-detection', '輪郭検出', 'Contour Detection', 'り', '物体の外形線を抽出する処理。', 2, 'g-kentei'),
    ('back-translation', '逆翻訳', 'Back Translation', 'ぎ', '翻訳→逆翻訳でデータ拡張や学習を行う手法。', 2, 'g-kentei'),
    ('federated-averaging', '連合平均化', 'Federated Averaging', 'れ', '分散クライアントの更新を平均してグローバルモデルを更新。', 2, 'g-kentei'),
    ('connected-components', '連結成分ラベリング', 'Connected Components', 'れ', '隣接ピクセル群にラベルを付与する処理。', 2, 'g-kentei'),
    ('weight-initialization', '重み初期化', 'Weight Initialization', 'お', '学習開始時の重み設定。収束速度と安定性に影響。', 2, 'g-kentei'),
    ('weight-decay', '重み減衰', 'Weight Decay', 'お', 'L2正則化と同等の重みペナルティ。AdamWで分離。', 2, 'g-kentei'),
    ('relation-extraction', '関係抽出', 'Relation Extraction', 'か', '文からエンティティ間の関係を抽出する。', 2, 'g-kentei'),
    ('static-quantization', '静的量子化', 'Static Quantization', 'せ', '校準データで量子化パラメータを事前決定する技法。', 2, 'g-kentei'),
    ('non-maximum-suppression', '非極大値抑制', 'Non-Maximum Suppression', 'ひ', '重複検出を除去する後処理。', 2, 'g-kentei'),
    ('pruning-unstructured', '非構造化剪定', 'Unstructured Pruning', 'ひ', '個別重みをゼロにする細かい剪定。', 2, 'g-kentei'),
    ('audio-language-model', '音声言語モデル', 'Audio-Language Model', 'お', '音声入力を理解・生成するマルチモーダルモデル。', 2, 'g-kentei'),
    ('facial-landmark', '顔ランドマーク', 'Facial Landmark', 'か', '目・鼻・口など顔の特徴点座標。', 2, 'g-kentei'),
    ('face-detection', '顔検出', 'Face Detection', 'か', '画像内の顔領域を見つけるタスク。', 2, 'g-kentei'),
    ('face-recognition', '顔認識', 'Face Recognition', 'か', '顔画像から個人を識別する深層学習応用。', 2, 'g-kentei'),
]
